"""Source-only final-nine bookkeeping preparation; no comparator import/run."""
from pathlib import Path
import ast,difflib,hashlib,json
P=Path(__file__).resolve().parent;R=P.parents[1];B=R/'build-layer-research';old=B/'reference-wave-map-t2-subset-comparison-held-v2-20261009';batch=B/'wave-map-native-t2-root-20261009/batch001';read=B/'reference-wave-map-t2-readback-held-20261009'
def load(p):return json.loads(Path(p).read_text(),parse_constant=lambda x:(_ for _ in ()).throw(ValueError(x)))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def pin(p):p=Path(p).resolve();return {'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size}
def dump(p,x):Path(p).write_text(json.dumps(x,indent=2,allow_nan=False)+'\n')
assert not (P/'registry.json').exists()
historical={str(q.resolve()):sha(q) for n in ('reference-wave-map-t2-subset-comparison-held-20261009','reference-wave-map-t2-subset-comparison-held-v2-20261009') for q in (B/n).rglob('*') if q.is_file()}
cases=load(old/'registry.json')['cases'];failed={'wave-map-N16-large-t2','c0-N16-large-t2','wave-map-N24-large-t2','wave-map-half-N24-large-t2','wave-map-N24-small-t2','wave-map-N32-large-t2'};complete=set(x['name'] for x in cases)-failed;assert complete=={'c0-N24-large-t2','c0-N32-large-t2','wave-map-N24-reference-long-t2'}
b=load(batch/'receipt.json');assert b['native_cases']==9 and b['passed_native_processes_and_provenance'] is False and len(b['cases'])==9
entries={};evidence=[]
for row in cases:
 name=row['name'];q=batch/name/'launch-receipt.json';n=load(q);h=sha(q);assert b['cases'][name]==h and n['mode']==row['mode'] and n['sources_before_after_equal'] is True
 entry={'status':'native_failed' if name in failed else 'completed_and_admitted','native_launch_receipt_path':str(q.resolve()),'native_launch_receipt_sha256':h}
 if name in failed:assert n['passed_native_process_and_provenance'] is False and (n['returncode']!=0 or n['error'] is not None)
 else:
  assert n['passed_native_process_and_provenance'] is True and n['returncode']==0 and n['error'] is None
  a=read/'attempts'/(name+'-001');o=load(a/'receipt.json');t=load(a/'analysis/receipt.json');assert o['returncode']==0 and o['passed_completed_t2_snapshot_gates'] and o['protected_before_after_equal'];assert t['passed_saved_snapshot_finite_and_diagnostic_gates'] and t['protected_inputs_before_after_equal'] and t['saved_arrays']==81 and t['target_time']==2 and t['N']==row['N'] and t['mode']==row['mode'] and t['reference']==(row['profile']=='reference');assert o['launch_receipt_sha256']==h and t['launch_receipt_sha256']==h and o['analyzer_receipt_sha256']==sha(a/'analysis/receipt.json') and t['snapshots_sha256']==sha(a/'analysis/snapshots.json')
  entry.update(completed_readback_attempt_directory=str(a.resolve()),completed_outer_receipt_sha256=sha(a/'receipt.json'),completed_analyzer_receipt_sha256=sha(a/'analysis/receipt.json'),completed_snapshots_sha256=sha(a/'analysis/snapshots.json'))
  evidence += [pin(a/'receipt.json'),pin(a/'analysis/receipt.json'),pin(a/'analysis/snapshots.json')]
 row['status']=entry['status'];row['evidence']=entry;entries[name]=entry;evidence.append(pin(q))
registry={'scope':'Final source-only registry: all original nine processes finished; six mandatory failed, three completed/admitted; no pending or scientific acceptance.','cases':cases,'non_overridable_known_native_failures':sorted(failed),'non_overridable_completed_cases':sorted(complete),'all_nine_statuses_explicit':True,'pending_allowed':False,'original_final_batch_receipt':pin(batch/'receipt.json'),'matrix_complete_and_admitted':False,'t6_admission':False,'t12_admission':False,'known_failure_provenance':'Exact original launch receipts and final batchreceipt verified during metadata preparation; no history/array interpretation.'};dump(P/'registry.json',registry)
s=(old/'compare_subset.py').read_text();original=s
changes=[("STATUS = {'pending', 'native_failed', 'completed_and_admitted'}", "STATUS = {'native_failed', 'completed_and_admitted'}"),
("    require(receipt['mode'] == registry_row['mode'], 'Wrong native mode for ' + name)\n", "    require(receipt['mode'] == registry_row['mode'], 'Wrong native mode for ' + name)\n    require(receipt['sources_before_after_equal'] is True, 'Original source provenance failed: ' + name)\n"),
("    analysis_path = pinned(attempt / 'analysis/receipt.json', outer['analyzer_receipt_sha256'], pins)", "    require(outer['analyzer_receipt_sha256'] == entry['completed_analyzer_receipt_sha256'], 'Frozen analyzer pin mismatch: ' + name)\n    analysis_path = pinned(attempt / 'analysis/receipt.json', entry['completed_analyzer_receipt_sha256'], pins)"),
("    rows_path = pinned(attempt / 'analysis/snapshots.json', analysis['snapshots_sha256'], pins)", "    require(analysis['snapshots_sha256'] == entry['completed_snapshots_sha256'], 'Frozen saved-JSON pin mismatch: ' + name)\n    rows_path = pinned(attempt / 'analysis/snapshots.json', entry['completed_snapshots_sha256'], pins)"),
("                        'completed_readback_recipe': READBACK / 'recipe.json'}", "                        'completed_readback_recipe': READBACK / 'recipe.json',\n                        'final_evidence_recipe': HERE / 'bookkeeping-recipe.json',\n                        'original_final_batch_receipt': LONG / 'batch001/receipt.json'}"),
("    known = set(registry['non_overridable_known_native_failures'])\n", "    known = set(registry['non_overridable_known_native_failures'])\n    require(len(known) == 6 and registry['pending_allowed'] is False, 'Wrong fixed final-failure set')\n    batch = load(LONG / 'batch001/receipt.json')\n    require(batch['native_cases'] == 9 and batch['passed_native_processes_and_provenance'] is False, 'Final batch status mismatch')\n    require(batch['cases'] == {name: auth['cases'][name]['native_launch_receipt_sha256'] for name in names}, 'Final batch/case pins mismatch')\n"),
("        require(status in STATUS, 'Unknown case status: ' + name)", "        require(status in STATUS, 'Unknown/pending final case status: ' + name)\n        require(status == row['status'] and entry == row['evidence'], 'Final frozen case cannot be relabeled: ' + name)"),
("        else:\n            require(isinstance(entry['reason'], str) and entry['reason'].strip(), 'Pending case needs explicit reason: ' + name)\n            cases[name] = {'status': 'pending', 'reason': entry['reason'], 't2_values': None}", "        else:\n            raise ValueError('Final registry has no pending branch: ' + name)"),
("    pending = [name for name in names if cases[name]['status'] == 'pending']", "    pending = []\n    require(set(failed) == known, 'All six original failures are mandatory')"),
("    all_admitted = len(admitted) == 9", "    require(len(admitted) == 3, 'Exactly three completed/admitted cases required')\n    all_admitted = False"),
("    return {'partial_matrix_diagnostic_only': True, 'fixed_registry_size': 9,", "    return {'final_fixed_case_bookkeeping_only': True, 'all_original_processes_finished': True,\n            'partial_matrix_diagnostic_only': True, 'fixed_registry_size': 9,"),
("            'all_nine_admitted': all_admitted, 'matrix_complete_and_admitted': all_admitted,", "            'all_nine_admitted': False, 'matrix_complete_and_admitted': False,\n            'matrix_status': 'finished_with_six_mandatory_failed_original_cases',")]
for a,z in changes:assert s.count(a)==1,a;s=s.replace(a,z)
(P/'compare_subset.py').write_text(s);(P/'run_subset.py').write_bytes((old/'run_subset.py').read_bytes());(P/'v2-to-v3-comparator.diff').write_text(''.join(difflib.unified_diff(original.splitlines(True),s.splitlines(True),fromfile='v2/compare_subset.py',tofile='v3/compare_subset.py')))
plan='''# HELD final-nine native bookkeeping v3\n\nAll nine original processes have finished. This fresh source-only v3 preserves v1/v2 unchanged. Six named failed original cases are mandatory native_failed and can never acquire t2 values from partial observations. C0N24, C0N32 and stationary waveN24 have exact successful native+completed wrapper+analyzer+saved-JSON pins. No pending status is allowed. Final batchreceipt must agree with all nine original receipt hashes.\n\nThe comparator/wrapper are HELD and have not been imported or executed. Root must supply a fresh completed_subset_comparison_authorized=true JSON binding every source pin and exact fixed case entry from the retained false template. Python-B run_subset.py ROOT_AUTHORIZATION withbytecodeoff will perform only completed saved-scalar bookkeeping. No native/source/probe/array call or operator/eigensolve/propagation is permitted. All named dependencies must be completed/admitted before any ratio is evaluated; failed dependencies produce not_evaluable, never surrogate endpoint values. Existing original numerical predicate thresholds remain unchanged.\n\nAll six candidate/control failures remain failed despite successful later saved-state observations. matrix_complete_and_admitted=false,t6_admission=false,t12_admission=false unconditionally. Completion of the nine processes is different from admission of the fixed scientific matrix. This report cannot authorize continuation, adoption, stability, convergence order, scri regularity or BH work. No partial histories or failed-state arrays are inspected.\n''';(P/'PLAN.md').write_text(plan)
recipe={'scope':'Source-only final-nine case bookkeeping; no execution or new scientific result.','registry':pin(P/'registry.json'),'original_final_batch_receipt':pin(batch/'receipt.json'),'evidence_pins':evidence,'command':['python3','-B',str(P/'run_subset.py'),'FRESH_ROOT_AUTHORIZATION'],'environment':{'PYTHONDONTWRITEBYTECODE':'1','OPENBLAS_NUM_THREADS':'1','VECLIB_MAXIMUM_THREADS':'1'},'fixed_failed_cases':sorted(failed),'fixed_completed_cases':sorted(complete),'pending_cases':[],'ratios_require_every_named_dependency_completed_and_admitted':True,'matrix_complete_and_admitted':False,'t6_admission':False,'t12_admission':False};dump(P/'bookkeeping-recipe.json',recipe)
sourcepaths={'PLAN.md':P/'PLAN.md','registry.json':P/'registry.json','compare_subset.py':P/'compare_subset.py','run_subset.py':P/'run_subset.py','original_native_PLAN':R/'docs/validation/hyperboloidal-reference-wave-map-native-preflights-20261009/native-preparation/PLAN.md','completed_readback_recipe':read/'recipe.json','final_evidence_recipe':P/'bookkeeping-recipe.json','original_final_batch_receipt':batch/'receipt.json'};sourcepins={k:sha(q) for k,q in sourcepaths.items()};assert sourcepins['original_native_PLAN']=='7955afb3db4b227c0fe885410255452b4fcb15e249ed97b2d52c2672c4697926'
dump(P/'authorization-template.json',{'completed_subset_comparison_authorized':False,'source_sha256':sourcepins,'cases':entries,'scope':'Retained exact false source-only template; root must create new authorization, never rewrite this template.'})
dump(P/'case-entry-schema.json',{'statuses':['native_failed','completed_and_admitted'],'pending_allowed':False,'entries_must_match_exact_frozen_registry_evidence':True,'six_failed_cases_mandatory':sorted(failed),'three_completed_cases_mandatory':sorted(complete)})
for q in (P/'compare_subset.py',P/'run_subset.py'):ast.parse(q.read_text())
for p,h in historical.items():assert sha(p)==h
readiness={'prepared_source_only':True,'execution_held':True,'comparator_imported_or_executed':False,'wrapper_executed':False,'AST_parse_only':True,'result_receipt_identity_fields_inspected':True,'snapshot_values_not_interpreted':True,'all9_exact_receipt_pins_verified':True,'all3_completed_wrapper_analyzer_saved_JSON_hash_chains_verified':True,'v1_v2_unchanged':True,'known_failed_cases':sorted(failed),'completed_cases':sorted(complete),'pending_cases':[],'source_pins':{str(q.resolve()):sourcepins[k] for k,q in sourcepaths.items()},'native_final_batch_receipt':pin(batch/'receipt.json'),'historical_v1_v2_files':historical,'new_scientific_queries':0,'native_steps':0,'matrix_complete_and_admitted':False,'t6_admission':False};dump(P/'readiness.json',readiness)
files={q.name:pin(q) for q in sorted(P.iterdir()) if q.is_file() and q.name not in {'source-index.json','preparation.stdout','preparation.stderr'}};dump(P/'source-index.json',{'scope':'HELD source-only final9 bookkeeping; no numerical execution','files':files,'execution_held':True,'matrix_complete_and_admitted':False,'t6_admission':False})
print(json.dumps({'source_index':pin(P/'source-index.json'),'registry':pin(P/'registry.json'),'recipe':pin(P/'bookkeeping-recipe.json'),'comparator':pin(P/'compare_subset.py'),'wrapper':pin(P/'run_subset.py'),'native_failures':6,'completed_admitted':3,'pending':0,'comparator_executed':False},indent=2))
