#!/usr/bin/env bash
set -euo pipefail

: "${CAMPAIGN_ROOT:?fresh campaign root required}"
: "${SOURCE_ROOT:?}"
: "${BUILD_ROOT:?}"
: "${FIXED_INPUT:?}"
: "${REPLAY_INPUT:?}"
: "${COEFFICIENT_FILE:?}"
: "${AUTHORITY_FILE:?}"

expected_source=684402aed9d5038cf864cf84449e160e7d1545e1
expected_tree=2666b75a7291b85349c0c4de46883178b0f4ea90
expected_kokkos=6739bc623081648af9e752b616d9671527922cbf
expected_exe=d1b9fa83a5dc2b2f8e9048465dda7d2b896c140880ea9e6af5eeb526421a7cfa
expected_cache=c369598df28b2ba1f1b78eeb862df9ef5bc7bb42c190ad776fbede82e2d3f8c8
expected_coeff=ff0993c390513c15d6aa65857a0a3c710f2e2c3faf5717d9d63245203ccf2d6b
expected_authority=874551cc68e7dab4d40b854b31ab6b42aff9d2eae0ca9faf5985c41ef14a589f

test ! -e "${CAMPAIGN_ROOT}"
case "${SLURM_JOB_QOS:-}" in
  shared_interactive|gpu_shared_interactive|gpu_shared_interactive_ss11) ;;
  *) printf 'unexpected QOS: %s\n' "${SLURM_JOB_QOS:-<missing>}" >&2; exit 2 ;;
esac
test "${SLURM_NNODES:-}" = 1
test "${SLURM_NTASKS:-}" = 2
# The shared-GPU QOS requires a 32-core reservation for one GPU.  Commands
# below request/use only 8 cores per rank, so at most 16 cores are active.
test "${SLURM_CPUS_PER_TASK:-}" = 16
test "${SLURM_GPUS_PER_NODE:-}" = 1

test "$(git -C "${SOURCE_ROOT}" rev-parse HEAD)" = "${expected_source}"
test "$(git -C "${SOURCE_ROOT}" rev-parse HEAD^{tree})" = "${expected_tree}"
test -z "$(git -C "${SOURCE_ROOT}" status --porcelain)"
test "$(git -C "${SOURCE_ROOT}/kokkos" rev-parse HEAD)" = "${expected_kokkos}"

athena="${BUILD_ROOT}/src/athena"
test -x "${athena}"
test "$(sha256sum "${athena}" | awk '{print $1}')" = "${expected_exe}"
test "$(sha256sum "${BUILD_ROOT}/CMakeCache.txt" | awk '{print $1}')" = "${expected_cache}"
test "$(sha256sum "${COEFFICIENT_FILE}" | awk '{print $1}')" = "${expected_coeff}"
test "$(sha256sum "${AUTHORITY_FILE}" | awk '{print $1}')" = "${expected_authority}"

profile=/pscratch/sd/h/hzhu/collapse-critical-perlmutter/workflow/profiles/perlmutter-a100.sh
python_bin=/global/common/software/nersc/pe/conda-envs/24.1.0/python-3.11/nersc-python/bin/python3
wrapper="${SOURCE_ROOT}/tst/test_suite/unit_tests/cartoon_mms_rank_wrapper.py"
export COLLAPSE_ROOT="${CAMPAIGN_ROOT}"
source "${profile}"
export OMP_NUM_THREADS=8 KOKKOS_NUM_THREADS=8
export MPICH_GPU_SUPPORT_ENABLED=1 MPICH_GPU_IPC_ENABLED=0
export MPICH_OFI_NIC_POLICY=GPU

mkdir -p "${CAMPAIGN_ROOT}/evidence" "${CAMPAIGN_ROOT}/qualification"
root="$(cd "${CAMPAIGN_ROOT}" && pwd)"
cp "${FIXED_INPUT}" "${root}/brill_vc_fixed_grid.athinput"
cp "${REPLAY_INPUT}" "${root}/brill_o4_common_tree.athinput"
cp "${COEFFICIENT_FILE}" "${root}/brill_global_48x32.coefficients"
cp "${AUTHORITY_FILE}" "${root}/n256_amr_history.jsonl"

finish() {
  code=$?
  trap - EXIT
  set +e
  printf '%s\n' "${code}" > "${root}/orchestration-status"
  git -C "${SOURCE_ROOT}" status --porcelain=v1 > "${root}/evidence/source-status.final"
  find "${root}" -type f ! -name SHA256SUMS ! -name SHA256SUMS.sha256 \
    -print0 | LC_ALL=C sort -z | xargs -0r sha256sum > "${root}/SHA256SUMS"
  (cd "${root}" && sha256sum -c SHA256SUMS >/dev/null)
  sha256sum "${root}/SHA256SUMS" > "${root}/SHA256SUMS.sha256"
  exit "${code}"
}
trap finish EXIT

env | LC_ALL=C sort > "${root}/evidence/environment.txt"
scontrol show job "${SLURM_JOB_ID}" > "${root}/evidence/slurm-job.txt"
scontrol show node "${SLURM_NODELIST}" -o > "${root}/evidence/node.txt"
{
  date --iso-8601=seconds
  git -C "${SOURCE_ROOT}" rev-parse HEAD HEAD^{tree}
  git -C "${SOURCE_ROOT}/kokkos" rev-parse HEAD
  sha256sum "${athena}" "${BUILD_ROOT}/CMakeCache.txt" \
    "${root}/brill_vc_fixed_grid.athinput" \
    "${root}/brill_o4_common_tree.athinput" \
    "${root}/brill_global_48x32.coefficients" \
    "${root}/n256_amr_history.jsonl"
  module list
} > "${root}/evidence/provenance.txt" 2>&1

run_gpu() {
  srun --nodes=1 --ntasks=1 --ntasks-per-node=1 --cpus-per-task=8 \
    --gpus-per-task=1 --gpu-bind=map_gpu:0 --cpu-bind=cores --exact \
    --kill-on-bad-exit=1 "$@"
}

# Device qualification must precede all Brill science cases.  The selected
# tests execute the production VC kernels and cover uniform, Cartoon-axis,
# static/dynamic AMR, restart, output, direct import, and topology paths.
regex='^athena[.]z4c_(vc|cartoon_axis_centered)'
# Perlmutter's CMake records /usr/bin/python3 (Python 3.6), while the test
# harnesses require the NERSC Python 3.11 environment.  Read CTest's json-v1
# inventory so test selection and arguments remain authoritative, replacing
# only that obsolete interpreter path.  Production C++ test commands remain
# byte-for-byte as generated by CMake.
ctest --test-dir "${BUILD_ROOT}" --show-only=json-v1 -R "${regex}" \
  > "${root}/qualification/ctest-inventory.json"
"${python_bin}" - "${root}/qualification/ctest-inventory.json" \
  "${BUILD_ROOT}" "${python_bin}" \
  > "${root}/qualification/cuda-ctest.log" 2>&1 <<'PY'
import json, os, pathlib, subprocess, sys, time

inventory = json.loads(pathlib.Path(sys.argv[1]).read_text())
build_root = pathlib.Path(sys.argv[2])
python = sys.argv[3]
assert inventory["kind"] == "ctestInfo"
assert inventory["version"]["major"] == 1
tests = inventory["tests"]
assert len(tests) == 30, [t["name"] for t in tests]
assert len({t["name"] for t in tests}) == len(tests)
for index, test in enumerate(tests, 1):
    command = list(test["command"])
    if command[0] == "/usr/bin/python3":
        command[0] = python
    # MPI harnesses already launch their production commands through the
    # CMake-recorded srun launcher.  Every other test gets its own one-rank
    # GPU-bound step so direct Athena/Kokkos invocations see the allocated GPU.
    if "--mpiexec" not in command:
        command = [
            "/usr/bin/srun", "--nodes=1", "--ntasks=1",
            "--ntasks-per-node=1", "--cpus-per-task=8",
            "--gpus-per-task=1", "--gpu-bind=map_gpu:0",
            "--cpu-bind=cores", "--exact", "--kill-on-bad-exit=1",
        ] + command
    timeout = 300.0
    for prop in test.get("properties", []):
        if prop["name"] == "TIMEOUT":
            timeout = float(prop["value"])
        assert prop["name"] not in {
            "DISABLED", "WILL_FAIL", "SKIP_RETURN_CODE",
            "SKIP_REGULAR_EXPRESSION",
        }
    print(f"START {index}/30 {test['name']}", flush=True)
    start = time.monotonic()
    result = subprocess.run(command, cwd=build_root, text=True,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            timeout=timeout, env=os.environ.copy())
    print(result.stdout, end="")
    print(f"END {index}/30 {test['name']} status={result.returncode} "
          f"seconds={time.monotonic()-start:.6f}", flush=True)
    if result.returncode != 0:
        raise SystemExit(result.returncode)
print("100% tests passed, 0 tests failed out of 30", flush=True)
PY
grep -Fx '100% tests passed, 0 tests failed out of 30' \
  "${root}/qualification/cuda-ctest.log" >/dev/null
printf 'PERLMUTTER_CUDA_VERTEX_TESTS_PASS\n' > "${root}/qualification/status"

run_case() {
  local family=$1 label=$2 nx1=$3 nx2=$4 mb1=$5 mb2=$6 tlim=$7
  shift 7
  local case_root="${root}/${family}/${label}"
  local bindings="${case_root}/rank-bindings"
  test ! -e "${case_root}"
  mkdir -p "${bindings}"
  local input=brill_vc_fixed_grid.athinput
  if [[ "${family}" = common_tree ]]; then input=brill_o4_common_tree.athinput; fi
  local command=(srun --nodes=1 --ntasks=1 --ntasks-per-node=1
    --cpus-per-task=8 --gpus-per-task=1 --gpu-bind=map_gpu:0
    --cpu-bind=cores --exact --kill-on-bad-exit=1
    "${python_bin}" "${wrapper}" --evidence-dir "${bindings}"
    --require-cuda -- "${athena}" -i "${root}/${input}"
    mesh/nx1="${nx1}" mesh/nx2="${nx2}"
    meshblock/nx1="${mb1}" meshblock/nx2="${mb2}"
    time/tlim="${tlim}" time/nlim=-1 job/basename="${label}"
    problem/brill_global_coefficients_file="${root}/brill_global_48x32.coefficients"
    problem/constraint_summary_file="${case_root}/${label}.constraints.dat"
    "$@")
  printf '%q ' "${command[@]}" > "${case_root}/command.txt"
  printf '\n' >> "${case_root}/command.txt"
  set +e
  (cd "${case_root}" && "${command[@]}" > stdout.log 2> stderr.log)
  status=$?
  set -e
  printf '%s\n' "${status}" > "${case_root}/exit-status"
  "${python_bin}" - "${bindings}" <<'PY'
import json, pathlib, sys
files = sorted(pathlib.Path(sys.argv[1]).glob("rank_binding_*.json"))
assert len(files) == 1, files
record = json.loads(files[0].read_text())
assert record["binding_verified"] is True, record
assert "NVIDIA A100-SXM4" in record["gpu_name"], record
assert record["selected_uuid"], record
PY
  if [[ ${status} -ne 0 ]]; then
    printf 'FAIL_CLOSED\n' > "${case_root}/disposition"
    return "${status}"
  fi
  grep -Fq 'Terminating on time limit' "${case_root}/stdout.log"
  printf 'REACHED_TLIM\n' > "${case_root}/disposition"
}

# Gate E: uniform VC O4 at a common early coordinate-time interval.
for spec in 'n128 64 128 16 16' 'n256 128 256 32 32' 'n512 256 512 64 64'; do
  read -r label nx1 nx2 mb1 mb2 <<<"${spec}"
  run_case fixed_grid "${label}" "${nx1}" "${nx2}" "${mb1}" "${mb2}" 0.5 \
    mesh_refinement/max_nmb_per_rank=64
done

# Gate F: replay the authenticated CC authority as topology-only geometry.
# t=5 exceeds the prior CC central proper-time turnover target tau_c~=3 while
# remaining far short of the prohibited long-collapse interval.
overall=0
for spec in 'n128 64 128 16 16 512' 'n256 128 256 32 32 512' 'n512 256 512 64 64 256'; do
  read -r label nx1 nx2 mb1 mb2 capacity <<<"${spec}"
  run_case common_tree "${label}" "${nx1}" "${nx2}" "${mb1}" "${mb2}" 5.0 \
    z4c/grid_centering=vertex \
    mesh_refinement/max_nmb_per_rank="${capacity}" \
    mesh_refinement/amr_history_mode=replay \
    mesh_refinement/amr_history_file="${root}/n256_amr_history.jsonl" \
    mesh_refinement/amr_history_topology_only_centering_compatibility=cell_to_vertex \
    mesh_refinement/amr_history_compatible_source_id=athena-0.1-git-d0d0b648bab09afb33453132075f1b813306526a \
    || overall=1
done

if [[ ${overall} -eq 0 ]]; then
  printf 'PERLMUTTER_VERTEX_BOUNDED_CAMPAIGN_PASS\n' > "${root}/status"
else
  printf 'PERLMUTTER_VERTEX_BOUNDED_CAMPAIGN_CASE_FAILURE\n' > "${root}/status"
fi
exit "${overall}"
