#!/usr/bin/env bash
set -euo pipefail
bundle_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
source "${bundle_dir}/contract.env"

required=(
  EXPECTED_SOURCE_COMMIT EXPECTED_SOURCE_TREE EXPECTED_SOURCE_KOKKOS
  SOURCE_ROOT SOURCE_PATH EXECUTABLE EXPECTED_EXECUTABLE_SHA256
  BASELINE_ROOT BASELINE_CASE EXPECTED_BASELINE_ROOT_MANIFEST_SHA256
  EXPECTED_BASELINE_DETACHED_SHA256 EXPECTED_BASELINE_HISTORY_SHA256
  PRIOR_FIXED_ROOT PRIOR_FIXED_CASE EXPECTED_PRIOR_FIXED_ROOT_MANIFEST_SHA256
  EXPECTED_PRIOR_FIXED_DETACHED_SHA256 EXPECTED_PRIOR_FIXED_HISTORY_SHA256
  EXPECTED_PRIOR_FIXED_LOG_SHA256 EXPECTED_PRIOR_FIXED_COMMAND_SHA256
  PREDECESSOR_ROOT EXPECTED_PREDECESSOR_JOB_ID
  EXPECTED_PREDECESSOR_ROOT_MANIFEST_SHA256 EXPECTED_PREDECESSOR_DETACHED_SHA256
  EXPECTED_PREDECESSOR_SACCT_SHA256 EXPECTED_PREDECESSOR_COMPARISON_SHA256
  EXPECTED_PREDECESSOR_TAU1_HISTORY_SHA256 EXPECTED_PREDECESSOR_TAU2_HISTORY_SHA256
  EXPECTED_PREDECESSOR_TAU1_LOG_SHA256 EXPECTED_PREDECESSOR_TAU2_LOG_SHA256
  PREDECESSOR_CASE_TAU1 PREDECESSOR_CASE_TAU2
  REMOTE_ROOT EXPECTED_JOB_NAME EXPECTED_ACCOUNT EXPECTED_NUMBERED_STEPS
  EXPECTED_RANKS EXPECTED_GPUS EXPECTED_NUM_LEVELS EXPECTED_MAX_REF_LEV
  EXPECTED_NMB_TOTAL_LIMIT TARGET_TLIM CASE_KO002 CASE_KO05
  CASE_ZERO_SHIFT_KO05
  INPUT_BASENAME EXPECTED_INPUT_SHA256 COEFFICIENT_BASENAME
  EXPECTED_COEFFICIENT_SHA256 EXPECTED_AMPLITUDE EXPECTED_ADM_MASS
  PROFILE_PATH EXPECTED_PROFILE_SHA256 PYTHON_BIN
)
for name in "${required[@]}"; do
  value=${!name:-}
  test -n "${value}"
  case "${value}" in
    *__UNSET__*|*__PLACEHOLDER__*)
      printf 'unbound contract field %s=%s\n' "${name}" "${value}" >&2
      exit 2
      ;;
  esac
done

test "${EXPECTED_NUMBERED_STEPS}" = 3
test "${EXPECTED_RANKS}" = 4
test "${EXPECTED_GPUS}" = 4
test "${EXPECTED_NUM_LEVELS}" = 21
test "${EXPECTED_MAX_REF_LEV}" = 20
test "${EXPECTED_NMB_TOTAL_LIMIT}" = 8192
test "${CASE_KO002}" != "${CASE_KO05}"
test "${CASE_KO05}" != "${CASE_ZERO_SHIFT_KO05}"
test "${REMOTE_ROOT}" != "/"
test "${REMOTE_ROOT}" != "${HOME}"
test "${SOURCE_ROOT}" != "${REMOTE_ROOT}"
test "${PRIOR_FIXED_ROOT}" != "${REMOTE_ROOT}"
test "${PREDECESSOR_ROOT}" != "${REMOTE_ROOT}"
