#!/bin/bash
set -euo pipefail
bundle_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
source "${bundle_dir}/contract.env"
required=(ATHENA_URL ATHENA_BRANCH EXPECTED_SOURCE_COMMIT EXPECTED_SOURCE_TREE
  EXPECTED_KOKKOS_COMMIT REMOTE_ROOT EXPECTED_JOB_NAME SOURCE_ROOT BUILD_ROOT
  EXECUTABLE PROFILE_PATH EXPECTED_PROFILE_SHA256 EXPECTED_TEMPLATE_SHA256
  EXPECTED_DRIVER_SHA256 EXPECTED_ANALYZER_SHA256 EXPECTED_RANK_WRAPPER_SHA256
  EXPECTED_CMAKE_SHA256 EXPECTED_OPERATOR_TABLE_SHA256 EXPECTED_NODES
  EXPECTED_MPI_RANKS EXPECTED_GPUS EXPECTED_CPUS_PER_TASK
  EXPECTED_NUMBERED_STEPS EXPECTED_ACCOUNT PYTHON_MODULE PYTHON_BIN
  EXPECTED_PYTHON_SHA256 EXPECTED_NUMPY_VERSION EXPECTED_H5PY_VERSION
  EXPECTED_SYMPY_VERSION)
required+=(EXPECTED_AXIS_TEST_REPAIR_PARENT EXPECTED_AXIS_TEST_REPAIR_PATCH_ID
  EXPECTED_AXIS_TEST_REPAIR_PATH EXPECTED_AXIS_TEST_SHA256
  EXPECTED_KERR_REPAIR_PARENT EXPECTED_KERR_REPAIR_PATCH_ID
  EXPECTED_KERR_REPAIR_PATHS
  EXPECTED_KERR_PGEN_SHA256 EXPECTED_KERR_STATIC_SHA256
  EXPECTED_PREDECESSOR_SOURCE_COMMIT EXPECTED_PREDECESSOR_SOURCE_TREE)
required+=(V1_INCOMPLETE_ROOT V1_FINAL_ROOT EXPECTED_V1_BUNDLE_MANIFEST_SHA256)
required+=(V2_INCOMPLETE_ROOT V2_FINAL_ROOT EXPECTED_V2_BUNDLE_MANIFEST_SHA256)
required+=(V3_ROOT V3_JOB_ID EXPECTED_V3_ROOT_MANIFEST_SHA256
  EXPECTED_V3_DETACHED_SHA256 EXPECTED_V3_SACCT_SHA256
  EXPECTED_V3_SOURCE_STATUS_SHA256 EXPECTED_V3_BUILD_ERR_SHA256)
required+=(V4_ROOT V4_JOB_ID EXPECTED_V4_ROOT_MANIFEST_SHA256
  EXPECTED_V4_DETACHED_SHA256 EXPECTED_V4_SACCT_SHA256
  EXPECTED_V4_SOURCE_STATUS_SHA256 EXPECTED_V4_CTEST_LOG_SHA256
  EXPECTED_V4_CTEST_ERR_SHA256 EXPECTED_V4_EXECUTABLE_SHA256)
for name in "${required[@]}"; do
  value=${!name:-}
  test -n "${value}"
  test "${value}" != __UNSET__
done
test "${EXPECTED_NUMBERED_STEPS}" = 3
test "${EXPECTED_MPI_RANKS}" = 4
test "${EXPECTED_GPUS}" = 4
test "${EXPECTED_CPUS_PER_TASK}" = 8
test "${SOURCE_ROOT}" = "${REMOTE_ROOT}/source/athenak"
test "${BUILD_ROOT}" = "${REMOTE_ROOT}/build/athena-cuda"
test "${EXECUTABLE}" = "${BUILD_ROOT}/src/athena"
test "${PYTHON_MODULE}" = python/3.12-26.1.0
test "${PYTHON_BIN}" = \
  /global/common/software/nersc/pe/conda-envs/26.1.0/python-3.12/nersc-python/bin/python3
