// Generated by analysis/pc_gh_clean_reduction/generate_halo_weights.py.
#ifndef PC_GH_HALO_WEIGHTS_HPP_
#define PC_GH_HALO_WEIGHTS_HPP_
#include "athena.hpp"
namespace pc_gh {
template <int ORDER>
KOKKOS_INLINE_FUNCTION
Real HaloDerivativeWeight(int point, int node) {
  if constexpr (ORDER == 2) {
    const Real weights[3][3] = {
      {-3.0/2.0, 2.0/1.0, -1.0/2.0},
      {-1.0/2.0, 0.0/1.0, 1.0/2.0},
      {1.0/2.0, -2.0/1.0, 3.0/2.0},
    };
    return weights[point][node];
  }
  if constexpr (ORDER == 4) {
    const Real weights[5][5] = {
      {-25.0/12.0, 4.0/1.0, -3.0/1.0, 4.0/3.0, -1.0/4.0},
      {-1.0/4.0, -5.0/6.0, 3.0/2.0, -1.0/2.0, 1.0/12.0},
      {1.0/12.0, -2.0/3.0, 0.0/1.0, 2.0/3.0, -1.0/12.0},
      {-1.0/12.0, 1.0/2.0, -3.0/2.0, 5.0/6.0, 1.0/4.0},
      {1.0/4.0, -4.0/3.0, 3.0/1.0, -4.0/1.0, 25.0/12.0},
    };
    return weights[point][node];
  }
  if constexpr (ORDER == 6) {
    const Real weights[7][7] = {
      {-49.0/20.0, 6.0/1.0, -15.0/2.0, 20.0/3.0, -15.0/4.0, 6.0/5.0, -1.0/6.0},
      {-1.0/6.0, -77.0/60.0, 5.0/2.0, -5.0/3.0, 5.0/6.0, -1.0/4.0, 1.0/30.0},
      {1.0/30.0, -2.0/5.0, -7.0/12.0, 4.0/3.0, -1.0/2.0, 2.0/15.0, -1.0/60.0},
      {-1.0/60.0, 3.0/20.0, -3.0/4.0, 0.0/1.0, 3.0/4.0, -3.0/20.0, 1.0/60.0},
      {1.0/60.0, -2.0/15.0, 1.0/2.0, -4.0/3.0, 7.0/12.0, 2.0/5.0, -1.0/30.0},
      {-1.0/30.0, 1.0/4.0, -5.0/6.0, 5.0/3.0, -5.0/2.0, 77.0/60.0, 1.0/6.0},
      {1.0/6.0, -6.0/5.0, 15.0/4.0, -20.0/3.0, 15.0/2.0, -6.0/1.0, 49.0/20.0},
    };
    return weights[point][node];
  }
  return 0.0;
}
}  // namespace pc_gh
#endif
