"""Write a compact status report from previously collected diagnostics."""
from pathlib import Path
import json
p=Path(__file__).resolve().parent;j=json.loads((p/'status.json').read_text())
lines=['# Local source-damping controls','',f'Collected: {j["collected_at_utc"]}.','', 'These existing runs use the fixed-stencil immutable MPI binary, G1 background-adapted gauge, sixth-order spatial derivatives, linear residual ghost extrapolation and no outer sponge. The domain is a displaced weak-field trumpet patch, x,y=1536–2048M and z=−1280…−768M, with dx=32M. It contains neither the horizon nor the physical star; matter feedback is zero. All long runs use the same 1e−8 compact smooth lapse bump with support radius 64M and eight 8³ blocks on four MPI ranks. This is outer-region vacuum evidence, not a full TDE stability result. The compact lapse bump excites a gauge response and only indirectly seeds constraints; a separately controlled physical-constraint pulse remains necessary to test stronger perturbations.','', '| Case | (kappa, eta, lapse damping) | Status | Latest history t/M | Theta RMS | max abs Theta |', '|---|---|---|---:|---:|---:|']
for name,c in j['cases'].items():
 cfg=c['config'];v=c.get('last',{});rates=tuple(float(cfg.get(k))for k in ['z4c/damp_kappa1','z4c/shift_eta','z4c/residual_lapse_damping']);lines.append(f'| {name} | {rates} | {c["status"]} | {c.get("last_history_M",0):.3f} | {v.get("theta_rms",0):.5g} | {v.get("theta_max",0):.5g} |')
lines +=['','The κ=0, η=.02, lapse damping=.01 weak-field control reached 50000M cleanly; all four final restart ranks match time/cycle and have finite payloads and positive full/ghost metric minors. Its late Θ values remain near numerical noise, so this is a clean bounded evolution, not proof of saturation, asymptotic stability or a full-domain TDE cure. The all-source-zero case stopped cleanly on walltime at 12212.4M, short of its 20000M target. All three nonzero-κ controls failed.','','`fast_weakfield` uses dt=3.2M, target 50000M and a 40-minute wall cap. The other cases use dt=.6M, target 20000M and a 30-minute cap. A cap stop is not target completion. `running_or_unconfirmed` means no clean completion marker yet.','', '![Collected constraint and gauge histories](local-controls.png)','', '## Norm and growth definitions','',j['norm_definition'],'','Displayed histories retain near-noise values. Growth fits require every sample in a sufficiently complete window to exceed the conservative analysis thresholds: Theta/H RMS1e−14, maxTheta1e−13, lapse/shift1e−11. These are analysis gates, not code clipping or universal measured roundoff floors. Early pulse decay may be fitted above the thresholds; small late secular drifts are displayed without claiming exponential growth or saturation.','', '| Case | Theta RMS window M | gamma /M | R squared |','|---|---:|---:|---:|']
for name,c in j['cases'].items():
 for f in c.get('fits',{}).get('theta_rms',[]):
  if f['fit_status']=='fitted':lines.append(f'| {name} | {f["actual_window_M"][0]:.1f}–{f["actual_window_M"][1]:.1f} | {f["gamma_M_inverse"]:.8g} | {f["R_squared"]:.7g} |')
lines+=['','## Failure localization and checkpoints','', 'The initial invalid primitive messages do not contain an exact RK time or rank. Their surrounding stdout lines give only a logging-order bracket, which can be affected by MPI buffering. The exact active invalid-state diagnostics are a later and different measurement. Finite active histories with zero badmetrics do not validate ghost metrics.']
for name,c in j['cases'].items():
 lines+=['',f'**{name}:**']
 first=c.get('first_printed_primitive_failure');events=c.get('active_invalid_events',[])
 if first:lines.append(f'First printed primitive failure: xyz={first["xyz_M"]}M, physical ghost depths={first["physical_ghost_depth_xyz"]}, determinant={first["determinant"]}; surrounding printed H times {first["preceding_printed_H_time_M"]} and {first["following_printed_H_time_M"]}M. This is not a located first injection time.')
 if events:lines.append(f'Active invalid-state abort at t={events[0]["time"]:.10g}M, cycle={int(events[0]["cycle"])}; {len(events)} rank events recorded in status.json.')
 cp=c.get('latest_checkpoint');val=c.get('checkpoint_validation')
 if c.get('final_log'):lines.append(f'Final application log: {c["final_log"]["reason"]}, time={c["final_log"]["time_M"]}M, cycle={c["final_log"]["cycle"]}.')
 if cp:lines.append(f'Latest available checkpoint: t={cp["time_M"]:.10g}M, cycle={cp["cycle"]}; older than latest history={cp["older_than_latest_history"]}. For failed runs, this checkpoint must not be used as the failure state.')
 if val:lines.append(f'Checkpoint validation: passed={val["passed"]}, matching all {val["ranks"]} rank headers, {val["blocks"]} blocks, all payload finite={val["all_payload_finite"]}, invalid full/ghost metric cells={val["invalid_metric_cells_including_ghosts"]}. Final checkpoint agrees with the final log time/cycle={val.get("matches_final_log_time_cycle")}. This validates saved state only.')
 if not first and not events:lines.append('No invalid-state or primitive failure was recorded. The separate final checkpoint check validates full/ghost metrics at the saved endpoint; the active history alone cannot do that.')
lines+=['','## Saved spatial checks','', 'Independent reconstruction of the saved checkpoints reproduces coincident proper-volume Theta RMS histories within 7e−16 relative. At 5000.4M, kappa01 peaks 80M from a face at(1936,1616,−1200); all_weak peaks near the pulse center at(1776,1776,−1008), 240M from a face. Neither is the first injection time nor the later failure state. Per-rank ownership, coordinates and distance-bin integrals are in the checkpoint-profile JSON files.','', '## Independent timestep check','', 'The separate stronger-pulse (1e−6) serial single 16³-block controls all reached 640M. Independent restart readback reproduces relative active residual L2 errors 0.000739528889 (dt1.6) and 0.006251014929 (dt3.2), versus dt.6. Their ratio 8.45 is consistent with third-order temporal error over this interval; this is neither spatial convergence nor long-time stability. This L2 combines residual variables and is not a physical energy norm. All three saved checkpoints are finite and have positive full/ghost metric minors. The recorded `checkpoint_dt` is not necessarily the final shortened integration step.','', '## Reproduce collection','', 'No command here launches AthenaK. Run from this directory:','', '```','OPENBLAS_NUM_THREADS=1 python3 collect.py --regression /path/to/checkout/tst/regression --validate-clean','OPENBLAS_NUM_THREADS=1 python3 plot.py','python3 report.py','```','', '`collect.py` imports the study checkpoint checker and records raw history arrays, profiles from existing log messages, growth windows, stopping markers and checkpoint availability. `timestep_review.py` independently rereads the already-completed timestep suite. `status.json` is authoritative for this completed collection. All five original processes have ended; this package launches no continuations.']
(p/'README.md').write_text('\n'.join(lines)+'\n')
