#!/usr/bin/env bash
set -euo pipefail
bundle_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
source "${bundle_dir}/contract.env"

required=(
  EXPECTED_SOURCE_COMMIT EXPECTED_SOURCE_TREE EXPECTED_SOURCE_KOKKOS SOURCE_PATH
  EXECUTABLE EXPECTED_EXECUTABLE_SHA256 V7_ROOT EXPECTED_V7_JOB_ID
  EXPECTED_V7_JOB_NAME EXPECTED_V7_ROOT_MANIFEST_SHA256 EXPECTED_V7_DETACHED_SHA256
  EXPECTED_V7_SACCT_SHA256 EXPECTED_V7_COMPARISON_SHA256
  EXPECTED_V7_ZERO_HISTORY_SHA256 EXPECTED_V7_ZERO_LOG_SHA256 V7_ZERO_CASE
  RESTART_BASENAME EXPECTED_RESTART_SHA256 EXPECTED_RESTART_BYTES REMOTE_ROOT
  EXPECTED_JOB_NAME EXPECTED_ACCOUNT EXPECTED_RANKS EXPECTED_GPUS EXPECTED_GPU_NAME
  EXPECTED_NUM_LEVELS EXPECTED_MAX_REF_LEV EXPECTED_NMB_TOTAL_LIMIT
  EXPECTED_MAX_NMB_PER_RANK TARGET_TLIM CASE_NAME OUTPUT_BASENAME PROFILE_PATH
  EXPECTED_COEFFICIENT_SHA256 EXPECTED_PROFILE_SHA256 PYTHON_BIN
)
for name in "${required[@]}"; do
  value=${!name:-}
  test -n "${value}"
  case "${value}" in
    *__UNSET__*|__*__) printf 'unbound contract field %s=%s\n' "${name}" "${value}" >&2; exit 2 ;;
  esac
done

test "${EXPECTED_RANKS}" = 1
test "${EXPECTED_GPUS}" = 1
test "${EXPECTED_GPU_NAME}" = NVIDIA_A100-SXM4-80GB
test "${EXPECTED_NUM_LEVELS}" = 21
test "${EXPECTED_MAX_REF_LEV}" = 20
test "${EXPECTED_NMB_TOTAL_LIMIT}" = 16384
test "${EXPECTED_MAX_NMB_PER_RANK}" = 16384
test "${TARGET_TLIM}" = 20.0
test "${EXPECTED_RESTART_BYTES}" = 1569397462
