// Generated by tst/unit/z4c/generate_z4c_cartoon_derivative_oracle.py.
// Do not edit by hand.
#ifndef PGEN_UNIT_TESTS_Z4C_CARTOON_DERIVATIVES_ORACLE_HPP_
#define PGEN_UNIT_TESTS_Z4C_CARTOON_DERIVATIVES_ORACLE_HPP_

#include "athena.hpp"

namespace z4c_mms {

struct AnalyticOracle {
  Real scalar;
  Real scalar_first[3];
  Real scalar_second[3][3];
  Real vector[3];
  Real vector_first[3][3];
  Real vector_second[3][3][3];
  Real tensor[6];
  Real tensor_first[6][3];
  Real tensor_second[6][3][3];
};

struct FieldValues { Real scalar; Real vector[3]; Real tensor[6]; };
struct ScalarOracle { Real first[3]; Real second[3][3]; };
struct VectorOracle { Real first[3]; Real second[3][3]; };
struct TensorOracle { Real first[3]; Real second[3][3]; };

KOKKOS_INLINE_FUNCTION
void EvaluateFieldValuesScalar(const Real x, const Real y, const Real z,
                FieldValues &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  oracle.scalar = ((11.0/100.0)*t0 + (11.0/100.0)*t1 + (3.0/100.0)*pow(z, 3) - z*((7.0/100.0)*t0 + (7.0/100.0)*t1) + (17.0/100.0)*z + 1)*exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*pow(z, 2));
}

KOKKOS_INLINE_FUNCTION
void EvaluateFieldValuesVector(const Real x, const Real y, const Real z,
                FieldValues &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = (9.0/100.0)*t0 + (9.0/100.0)*t1 - 1.0/25.0*t2 + (13.0/100.0)*z + 7.0/10.0;
  const Real t4 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t5 = t4*x;
  const Real t6 = (7.0/100.0)*t0 + (7.0/100.0)*t1 + (1.0/50.0)*t2 - 2.0/25.0*z + 3.0/10.0;
  const Real t7 = t4*y;
  oracle.vector[0] = t3*t5 - t6*t7;
  oracle.vector[1] = t4*(-3.0/50.0*t0 - 3.0/50.0*t1 + z*((1.0/20.0)*t0 + (1.0/20.0)*t1) + (19.0/100.0)*z - 1.0/5.0);
  oracle.vector[2] = t3*t7 + t5*t6;
}

KOKKOS_INLINE_FUNCTION
void EvaluateFieldValuesTensorA(const Real x, const Real y, const Real z,
                FieldValues &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t4 = (3.0/100.0)*t0 + (3.0/100.0)*t1;
  const Real t5 = t4 - 1.0/20.0*z + 21.0/100.0;
  const Real t6 = t3*x;
  const Real t7 = t3*(-1.0/25.0*t0 - 1.0/25.0*t1 + (1.0/50.0)*t2 + (7.0/100.0)*z - 3.0/10.0);
  oracle.tensor[0] = t0*t7 + t3*((1.0/20.0)*t0 + (1.0/20.0)*t1 + (3.0/25.0)*z + 11.0/10.0) - 2*t5*t6*y;
  oracle.tensor[1] = -t3*y*(-t4 + (1.0/25.0)*z + 7.0/50.0) + t6*((1.0/50.0)*t0 + (1.0/50.0)*t1 + (9.0/100.0)*z - 17.0/100.0);
  oracle.tensor[2] = t3*t5*(t0 - t1) + t7*x*y;
}

KOKKOS_INLINE_FUNCTION
void EvaluateFieldValuesTensorB(const Real x, const Real y, const Real z,
                FieldValues &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t4 = (1.0/50.0)*t0 + (1.0/50.0)*t1;
  const Real t5 = (3.0/100.0)*t0 + (3.0/100.0)*t1;
  const Real t6 = t3*x;
  oracle.tensor[3] = t3*((2.0/25.0)*t0 + (2.0/25.0)*t1 - t4*z - 11.0/100.0*z + 9.0/10.0);
  oracle.tensor[4] = t3*y*(t4 + (9.0/100.0)*z - 17.0/100.0) + t6*(-t5 + (1.0/25.0)*z + 7.0/50.0);
  oracle.tensor[5] = t1*t3*(-1.0/25.0*t0 - 1.0/25.0*t1 + (1.0/50.0)*t2 + (7.0/100.0)*z - 3.0/10.0) + t3*((1.0/20.0)*t0 + (1.0/20.0)*t1 + (3.0/25.0)*z + 11.0/10.0) + 2*t6*y*(t5 - 1.0/20.0*z + 21.0/100.0);
}

KOKKOS_INLINE_FUNCTION
void EvaluateFieldValues(const Real x, const Real y, const Real z,
                         FieldValues &oracle) {
  EvaluateFieldValuesScalar(x, y, z, oracle);
  EvaluateFieldValuesVector(x, y, z, oracle);
  EvaluateFieldValuesTensorA(x, y, z, oracle);
  EvaluateFieldValuesTensorB(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateScalarOracleFirst(const Real x, const Real y, const Real z,
                ScalarOracle &oracle) {
  const Real t0 = (7.0/50.0)*z;
  const Real t1 = pow(x, 2);
  const Real t2 = pow(y, 2);
  const Real t3 = pow(z, 2);
  const Real t4 = exp(-1.0/5.0*t1 - 1.0/5.0*t2 - 1.0/5.0*t3);
  const Real t5 = (7.0/100.0)*t1 + (7.0/100.0)*t2;
  const Real t6 = (2.0/5.0)*t4*((11.0/100.0)*t1 + (11.0/100.0)*t2 - t5*z + (3.0/100.0)*pow(z, 3) + (17.0/100.0)*z + 1);
  oracle.first[0] = t4*(-t0*x + (11.0/50.0)*x) - t6*x;
  oracle.first[1] = t4*((9.0/100.0)*t3 - t5 + 17.0/100.0) - t6*z;
  oracle.first[2] = t4*(-t0*y + (11.0/50.0)*y) - t6*y;
}

KOKKOS_INLINE_FUNCTION
void EvaluateScalarOracleSecond(const Real x, const Real y, const Real z,
                ScalarOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = 7*z;
  const Real t2 = t1 - 11;
  const Real t3 = 4*t2;
  const Real t4 = pow(y, 2);
  const Real t5 = pow(z, 3);
  const Real t6 = t0 + t4;
  const Real t7 = 11*t0 - t1*t6 + 11*t4 + 3*t5 + 17*z + 100;
  const Real t8 = (1.0/5.0)*t7;
  const Real t9 = 55 - 35*z;
  const Real t10 = pow(z, 2);
  const Real t11 = exp(-1.0/5.0*t0 - 1.0/5.0*t10 - 1.0/5.0*t4);
  const Real t12 = (1.0/250.0)*t11;
  const Real t13 = 2*z;
  const Real t14 = 7*t0 - 9*t10 + 7*t4;
  const Real t15 = t12*(t13*t2 + t14 + (2.0/5.0)*t7*z - 52);
  const Real t16 = t15*x;
  const Real t17 = (1.0/125.0)*t11*x*y*((11.0/5.0)*t0 + (11.0/5.0)*t4 + (3.0/5.0)*t5 - 7.0/5.0*t6*z + (87.0/5.0)*z - 2);
  const Real t18 = t15*y;
  oracle.second[0][0] = t12*(t0*t3 + t8*(2*t0 - 5) + t9);
  oracle.second[0][1] = t16;
  oracle.second[0][2] = t17;
  oracle.second[1][0] = t16;
  oracle.second[1][1] = t12*(t13*(t14 - 17) + t8*(2*t10 - 5) + 45*z);
  oracle.second[1][2] = t18;
  oracle.second[2][0] = t17;
  oracle.second[2][1] = t18;
  oracle.second[2][2] = t12*(t3*t4 + t8*(2*t4 - 5) + t9);
}

KOKKOS_INLINE_FUNCTION
void EvaluateScalarOracle(const Real x, const Real y, const Real z,
                          ScalarOracle &oracle) {
  EvaluateScalarOracleFirst(x, y, z, oracle);
  EvaluateScalarOracleSecond(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle0First(const Real x, const Real y, const Real z,
                VectorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t4 = t3*((9.0/100.0)*t0 + (9.0/100.0)*t1 - 1.0/25.0*t2 + (13.0/100.0)*z + 7.0/10.0);
  const Real t5 = (2.0/25.0)*z;
  const Real t6 = (7.0/100.0)*t0 + (7.0/100.0)*t1 + (1.0/50.0)*t2 - t5 + 3.0/10.0;
  const Real t7 = t3*t6;
  const Real t8 = x*y;
  const Real t9 = (2.0/5.0)*t4;
  oracle.first[0] = (9.0/50.0)*t0*t3 - t0*t9 - 7.0/50.0*t3*x*y + t4 + (2.0/5.0)*t7*t8;
  oracle.first[1] = (2.0/5.0)*t3*t6*y*z + t3*x*(13.0/100.0 - t5) - t3*y*((1.0/25.0)*z - 2.0/25.0) - t9*x*z;
  oracle.first[2] = (2.0/5.0)*t1*t3*t6 - 7.0/50.0*t1*t3 + (9.0/50.0)*t3*x*y - t7 - t8*t9;
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle0Second(const Real x, const Real y, const Real z,
                VectorOracle &oracle) {
  const Real t0 = pow(x, 3);
  const Real t1 = pow(x, 2);
  const Real t2 = t1*y;
  const Real t3 = pow(y, 2);
  const Real t4 = pow(z, 2);
  const Real t5 = 9*t1 + 9*t3 - 4*t4 + 13*z + 70;
  const Real t6 = t5*x;
  const Real t7 = 8*z;
  const Real t8 = 2*t4;
  const Real t9 = 7*t1 + 7*t3 - t7 + t8 + 30;
  const Real t10 = 5*y;
  const Real t11 = t10*t9;
  const Real t12 = 2*t5;
  const Real t13 = 2*t9;
  const Real t14 = exp(-1.0/5.0*t1 - 1.0/5.0*t3 - 1.0/5.0*t4);
  const Real t15 = (1.0/1250.0)*t14;
  const Real t16 = x*y;
  const Real t17 = t16*z;
  const Real t18 = t1*z;
  const Real t19 = z - 2;
  const Real t20 = 40*t19;
  const Real t21 = t7 - 13;
  const Real t22 = 10*z;
  const Real t23 = t9*y;
  const Real t24 = (1.0/2500.0)*t14*(10*t1*t21 + t16*t20 + 140*t17 + 4*t18*t5 - 180*t18 - t22*t5 - 4*t23*x*z - 200*z + 325);
  const Real t25 = t3*x;
  const Real t26 = 5*t9;
  const Real t27 = t15*(-t10*t5 + t12*t2 - t13*t25 - 180*t2 + 140*t25 + t26*x - 175*x + 225*y);
  const Real t28 = y*z;
  const Real t29 = t21*x;
  const Real t30 = -5*t6;
  const Real t31 = t3*z;
  const Real t32 = 2*t6;
  const Real t33 = t15*(t10*t29 - t13*t31 - 90*t17 + 20*t19*t3 + t26*z + t28*t32 + 70*t31 - 50*z + 100);
  const Real t34 = pow(y, 3);
  oracle.second[0][0] = t15*(t0*t12 - 180*t0 + t11 - t13*t2 + 140*t2 - 15*t6 + 675*x - 175*y);
  oracle.second[0][1] = t24;
  oracle.second[0][2] = t27;
  oracle.second[1][0] = t24;
  oracle.second[1][1] = t15*(t11 + t20*t28 + t22*t29 - t23*t8 + t30 + t6*t8 - 100*x - 50*y);
  oracle.second[1][2] = t33;
  oracle.second[2][0] = t27;
  oracle.second[2][1] = t33;
  oracle.second[2][2] = t15*(-t13*t34 + 15*t23 - 180*t25 + t3*t32 + t30 + 140*t34 + 225*x - 525*y);
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle0(const Real x, const Real y, const Real z,
                           VectorOracle &oracle) {
  EvaluateVectorOracle0First(x, y, z, oracle);
  EvaluateVectorOracle0Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle1First(const Real x, const Real y, const Real z,
                VectorOracle &oracle) {
  const Real t0 = (1.0/10.0)*z;
  const Real t1 = pow(x, 2);
  const Real t2 = pow(y, 2);
  const Real t3 = exp(-1.0/5.0*t1 - 1.0/5.0*t2 - 1.0/5.0*pow(z, 2));
  const Real t4 = (1.0/20.0)*t1 + (1.0/20.0)*t2;
  const Real t5 = (2.0/5.0)*t3*(-3.0/50.0*t1 - 3.0/50.0*t2 + t4*z + (19.0/100.0)*z - 1.0/5.0);
  oracle.first[0] = t3*(t0*x - 3.0/25.0*x) - t5*x;
  oracle.first[1] = t3*(t4 + 19.0/100.0) - t5*z;
  oracle.first[2] = t3*(t0*y - 3.0/25.0*y) - t5*y;
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle1Second(const Real x, const Real y, const Real z,
                VectorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = 5*z;
  const Real t3 = 6*t0 + 6*t1 - t2*(t0 + t1);
  const Real t4 = t3 - 19*z + 20;
  const Real t5 = t2 - 6;
  const Real t6 = 20*t5;
  const Real t7 = 150 - 125*z;
  const Real t8 = pow(z, 2);
  const Real t9 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t8);
  const Real t10 = (1.0/1250.0)*t9;
  const Real t11 = 10*z;
  const Real t12 = t10*(-25*t0 - 25*t1 - t11*t5 - 2*t4*z + 30);
  const Real t13 = t12*x;
  const Real t14 = -1.0/625.0*t9*x*y*(t3 + 31*z - 40);
  const Real t15 = t12*y;
  oracle.second[0][0] = t10*(-t0*t6 - t4*(2*t0 - 5) - t7);
  oracle.second[0][1] = t13;
  oracle.second[0][2] = t14;
  oracle.second[1][0] = t13;
  oracle.second[1][1] = -t10*(t11*(5*t0 + 5*t1 + 19) + t4*(2*t8 - 5));
  oracle.second[1][2] = t15;
  oracle.second[2][0] = t14;
  oracle.second[2][1] = t15;
  oracle.second[2][2] = t10*(-t1*t6 - t4*(2*t1 - 5) - t7);
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle1(const Real x, const Real y, const Real z,
                           VectorOracle &oracle) {
  EvaluateVectorOracle1First(x, y, z, oracle);
  EvaluateVectorOracle1Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle2First(const Real x, const Real y, const Real z,
                VectorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t4 = (7.0/50.0)*t3;
  const Real t5 = (2.0/25.0)*z;
  const Real t6 = t3*((7.0/100.0)*t0 + (7.0/100.0)*t1 + (1.0/50.0)*t2 - t5 + 3.0/10.0);
  const Real t7 = t3*((9.0/100.0)*t0 + (9.0/100.0)*t1 - 1.0/25.0*t2 + (13.0/100.0)*z + 7.0/10.0);
  const Real t8 = (2.0/5.0)*t7;
  const Real t9 = x*y;
  const Real t10 = (2.0/5.0)*t6;
  oracle.first[0] = -t0*t10 + t0*t4 + (9.0/50.0)*t3*x*y + t6 - t8*t9;
  oracle.first[1] = -t10*x*z + t3*x*((1.0/25.0)*z - 2.0/25.0) + t3*y*(13.0/100.0 - t5) - t8*y*z;
  oracle.first[2] = (9.0/50.0)*t1*t3 - t1*t8 - t10*t9 + t4*t9 + t7;
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle2Second(const Real x, const Real y, const Real z,
                VectorOracle &oracle) {
  const Real t0 = pow(x, 3);
  const Real t1 = pow(x, 2);
  const Real t2 = t1*y;
  const Real t3 = 8*z;
  const Real t4 = pow(y, 2);
  const Real t5 = pow(z, 2);
  const Real t6 = 2*t5;
  const Real t7 = 7*t1 - t3 + 7*t4 + t6 + 30;
  const Real t8 = t7*x;
  const Real t9 = 9*t1 + 9*t4 - 4*t5 + 13*z + 70;
  const Real t10 = 5*t9;
  const Real t11 = -t10*y;
  const Real t12 = 2*t7;
  const Real t13 = 2*t9;
  const Real t14 = exp(-1.0/5.0*t1 - 1.0/5.0*t4 - 1.0/5.0*t5);
  const Real t15 = (1.0/1250.0)*t14;
  const Real t16 = x*y;
  const Real t17 = t16*z;
  const Real t18 = z - 2;
  const Real t19 = t3 - 13;
  const Real t20 = 5*t7;
  const Real t21 = t15*(-20*t1*t18 + 2*t1*t7*z - 70*t1*z - 90*t17 + 5*t19*x*y - t20*z + 2*t9*x*y*z + 50*z - 100);
  const Real t22 = 180*t4;
  const Real t23 = t4*x;
  const Real t24 = t15*(-t10*x + t12*t2 + t13*t23 - 140*t2 - t20*y - t22*x + 225*x + 175*y);
  const Real t25 = 40*t18;
  const Real t26 = 10*z;
  const Real t27 = -5*t8;
  const Real t28 = t9*y;
  const Real t29 = (1.0/2500.0)*t14*(-t16*t25 - 140*t17 + 10*t19*t4 - t22*z - t26*t9 + 4*t4*t9*z + 4*t7*x*y*z - 200*z + 325);
  const Real t30 = pow(y, 3);
  oracle.second[0][0] = t15*(t0*t12 - 140*t0 + t11 + t13*t2 - 180*t2 - 15*t8 + 525*x + 225*y);
  oracle.second[0][1] = t21;
  oracle.second[0][2] = t24;
  oracle.second[1][0] = t21;
  oracle.second[1][1] = t15*(t11 + t19*t26*y - t25*x*z + t27 + t28*t6 + t6*t8 + 50*x - 100*y);
  oracle.second[1][2] = t29;
  oracle.second[2][0] = t24;
  oracle.second[2][1] = t29;
  oracle.second[2][2] = t15*(t13*t30 - 140*t23 + t27 - 15*t28 - 180*t30 + 2*t4*t8 + 175*x + 675*y);
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle2(const Real x, const Real y, const Real z,
                           VectorOracle &oracle) {
  EvaluateVectorOracle2First(x, y, z, oracle);
  EvaluateVectorOracle2Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateVectorOracle(const int component, const Real x, const Real y,
                          const Real z, VectorOracle &oracle) {
  if (component == 0) EvaluateVectorOracle0(x, y, z, oracle);
  if (component == 1) EvaluateVectorOracle1(x, y, z, oracle);
  if (component == 2) EvaluateVectorOracle2(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle0First(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t4 = t3*pow(x, 3);
  const Real t5 = (3.0/25.0)*t3;
  const Real t6 = t3*x;
  const Real t7 = (1.0/50.0)*t0 + (1.0/50.0)*t1 + (6.0/125.0)*z + 11.0/25.0;
  const Real t8 = 2*t3;
  const Real t9 = (3.0/100.0)*t0 + (3.0/100.0)*t1 - 1.0/20.0*z + 21.0/100.0;
  const Real t10 = t9*y;
  const Real t11 = -1.0/25.0*t0 - 1.0/25.0*t1 + (1.0/50.0)*t2 + (7.0/100.0)*z - 3.0/10.0;
  const Real t12 = (2.0/5.0)*t11;
  const Real t13 = t0*t3;
  const Real t14 = t3*t7;
  const Real t15 = t13*y;
  oracle.first[0] = (4.0/5.0)*t0*t3*t9*y - t0*t5*y - t10*t8 + 2*t11*t3*x - t12*t4 + (1.0/10.0)*t3*x - 2.0/25.0*t4 - t6*t7;
  oracle.first[1] = (4.0/5.0)*t10*t6*z - t12*t13*z + t13*((1.0/25.0)*z + 7.0/100.0) - t14*z + (1.0/10.0)*t3*x*y + t5;
  oracle.first[2] = (4.0/5.0)*t1*t3*t9*x - t1*t5*x - t12*t15 - t14*y - 2.0/25.0*t15 + (1.0/10.0)*t3*y - t8*t9*x;
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle0Second(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = x*y;
  const Real t1 = 450*t0;
  const Real t2 = pow(x, 2);
  const Real t3 = pow(x, 4);
  const Real t4 = pow(y, 2);
  const Real t5 = 125*t4;
  const Real t6 = pow(z, 2);
  const Real t7 = pow(x, 3);
  const Real t8 = t7*y;
  const Real t9 = 3*t2 + 3*t4 - 5*z + 21;
  const Real t10 = 5*t2;
  const Real t11 = t10 + 5*t4 + 12*z + 110;
  const Real t12 = 2*t11;
  const Real t13 = 4*t9;
  const Real t14 = 4*t2;
  const Real t15 = 4*t4;
  const Real t16 = 2*t6;
  const Real t17 = t14 + t15 - t16 - 7*z + 30;
  const Real t18 = 2*t17;
  const Real t19 = (1.0/1250.0)*exp(-1.0/5.0*t2 - 1.0/5.0*t4 - 1.0/5.0*t6);
  const Real t20 = 50*x;
  const Real t21 = 50*y;
  const Real t22 = t7*z;
  const Real t23 = 60*y;
  const Real t24 = t2*z;
  const Real t25 = 4*z + 7;
  const Real t26 = x*z;
  const Real t27 = 10*t9;
  const Real t28 = y*z;
  const Real t29 = t14*t9;
  const Real t30 = 10*t17;
  const Real t31 = t19*(t12*t26 - t18*t22 - t2*t21 - t20*z + 40*t22 + t23*t24 - 5*t25*t7 + 25*t25*x + t26*t30 + t27*t28 - t28*t29 - 60*x + 125*y);
  const Real t32 = t2*t4;
  const Real t33 = t19*(t0*t12 + t0*t30 - 300*t0 - t18*t8 + t2*t27 - 225*t2 + t27*t4 - t29*t4 + 120*t32 - 225*t4 + 80*t8 + 125*z - 525);
  const Real t34 = -5*t17*t2;
  const Real t35 = t19*(-t10*t25*y + 2*t11*y*z - t15*t26*t9 - t18*t2*t28 + 40*t2*y*z - t20*t4 - t21*z - t23 + 60*t4*x*z + 10*t9*x*z + 125*x);
  const Real t36 = pow(y, 3);
  oracle.second[0][0] = t19*(30*t0*t9 - t1 + t12*t2 - t13*t8 + 25*t17*t2 - t18*t3 - 725*t2 + 80*t3 - t5 + 50*t6 + 120*t8 + 115*z - 1175);
  oracle.second[0][1] = t31;
  oracle.second[0][2] = t33;
  oracle.second[1][0] = t31;
  oracle.second[1][1] = t19*(-t0*t13*t6 - 100*t0*z + 2*t11*t6 - t16*t17*t2 + 25*t2 - 10*t24*t25 - t34 - 25*t4 + 10*t9*x*y - 180*z - 550);
  oracle.second[1][2] = t35;
  oracle.second[2][0] = t33;
  oracle.second[2][1] = t35;
  oracle.second[2][2] = t19*(-t1 + 2*t11*t4 - t13*t36*x - t18*t32 + 80*t2*t4 - 125*t2 - t34 + 120*t36*x - t5 + 30*t9*x*y - 60*z - 425);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle0(const Real x, const Real y, const Real z,
                           TensorOracle &oracle) {
  EvaluateTensorOracle0First(x, y, z, oracle);
  EvaluateTensorOracle0Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle1First(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*pow(z, 2));
  const Real t3 = (1.0/25.0)*t2;
  const Real t4 = t2*((1.0/50.0)*t0 + (1.0/50.0)*t1 + (9.0/100.0)*z - 17.0/100.0);
  const Real t5 = -3.0/100.0*t0 - 3.0/100.0*t1 + (1.0/25.0)*z + 7.0/50.0;
  const Real t6 = t2*t5;
  const Real t7 = (2.0/5.0)*t6;
  const Real t8 = (2.0/5.0)*t4;
  const Real t9 = t3*y;
  const Real t10 = t8*x;
  oracle.first[0] = t0*t3 - t0*t8 + (3.0/50.0)*t2*x*y + t4 + t7*x*y;
  oracle.first[1] = -t10*z + (2.0/5.0)*t2*t5*y*z + (9.0/100.0)*t2*x - t9;
  oracle.first[2] = (3.0/50.0)*t1*t2 + t1*t7 - t10*y - t6 + t9*x;
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle1Second(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 3);
  const Real t1 = pow(x, 2);
  const Real t2 = t1*y;
  const Real t3 = 2*t1;
  const Real t4 = pow(y, 2);
  const Real t5 = 2*t4;
  const Real t6 = t3 + t5 + 9*z - 17;
  const Real t7 = t6*x;
  const Real t8 = 4*z;
  const Real t9 = 3*t1 + 3*t4 - t8 - 14;
  const Real t10 = 5*t9;
  const Real t11 = -t10*y;
  const Real t12 = t9*y;
  const Real t13 = pow(z, 2);
  const Real t14 = exp(-1.0/5.0*t1 - 1.0/5.0*t13 - 1.0/5.0*t4);
  const Real t15 = (1.0/1250.0)*t14;
  const Real t16 = x*y;
  const Real t17 = t16*z;
  const Real t18 = 40*z;
  const Real t19 = (1.0/2500.0)*t14*(-t1*t18 + t1*t6*t8 - 90*t1 + t16*t8*t9 + 40*t16 - 60*t17 - 10*t6*z + 225);
  const Real t20 = t4*x;
  const Real t21 = t6*y;
  const Real t22 = t15*(-t10*x - 40*t2 - 60*t20 + t21*t3 - 5*t21 + t5*t9*x + 75*x + 50*y);
  const Real t23 = -5*t7;
  const Real t24 = 2*t13;
  const Real t25 = t15*(-t10*z - 45*t16 - 20*t17 + 2*t4*t9*z - 30*t4*z + 20*t4 + 2*t6*x*y*z - 50);
  const Real t26 = pow(y, 3);
  oracle.second[0][0] = t15*(2*t0*t6 - 40*t0 + t11 + t12*t3 - 60*t2 - 15*t7 + 150*x + 75*y);
  oracle.second[0][1] = t19;
  oracle.second[0][2] = t22;
  oracle.second[1][0] = t19;
  oracle.second[1][1] = t15*(t11 + t12*t24 + t18*y + t23 + t24*t7 - 90*x*z);
  oracle.second[1][2] = t25;
  oracle.second[2][0] = t22;
  oracle.second[2][1] = t25;
  oracle.second[2][2] = t15*(-15*t12 - 40*t20 + t23 + 2*t26*t9 - 60*t26 + t5*t7 + 50*x + 225*y);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle1(const Real x, const Real y, const Real z,
                           TensorOracle &oracle) {
  EvaluateTensorOracle1First(x, y, z, oracle);
  EvaluateTensorOracle1Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle2First(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t4 = t3*y;
  const Real t5 = t0 - t1;
  const Real t6 = (3.0/100.0)*t0 + (3.0/100.0)*t1 - 1.0/20.0*z + 21.0/100.0;
  const Real t7 = -1.0/25.0*t0 - 1.0/25.0*t1 + (1.0/50.0)*t2 + (7.0/100.0)*z - 3.0/10.0;
  const Real t8 = t3*t7;
  const Real t9 = t8*y;
  const Real t10 = (2.0/5.0)*x;
  const Real t11 = t3*t5;
  const Real t12 = t11*t6;
  const Real t13 = (2.0/5.0)*t12;
  oracle.first[0] = -2.0/25.0*t0*t4 - 2.0/5.0*t0*t9 - t10*t12 + (3.0/50.0)*t3*t5*x + 2*t3*t6*x + t3*t7*y;
  oracle.first[1] = -t10*t9*z - 1.0/20.0*t11 - t13*z + t3*x*y*((1.0/25.0)*z + 7.0/100.0);
  oracle.first[2] = -2.0/25.0*t1*t3*x - 2.0/5.0*t1*t8*x - t13*y + (3.0/50.0)*t3*t5*y + t3*t7*x - 2*t4*t6;
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle2Second(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = 125*z;
  const Real t2 = pow(x, 3);
  const Real t3 = pow(y, 2);
  const Real t4 = 3*t0 + 3*t3 - 5*z + 21;
  const Real t5 = 20*t4;
  const Real t6 = t0 - t3;
  const Real t7 = 60*t6;
  const Real t8 = 4*t0;
  const Real t9 = 4*t3;
  const Real t10 = pow(z, 2);
  const Real t11 = 2*t10;
  const Real t12 = -t11 + t8 + t9 - 7*z + 30;
  const Real t13 = 2*t12;
  const Real t14 = t4*t6;
  const Real t15 = 5*t14;
  const Real t16 = x*y;
  const Real t17 = -15*t12*x*y + t15 + 300*t16;
  const Real t18 = exp(-1.0/5.0*t0 - 1.0/5.0*t10 - 1.0/5.0*t3);
  const Real t19 = (1.0/1250.0)*t18;
  const Real t20 = 4*z;
  const Real t21 = t20 + 7;
  const Real t22 = 10*t21;
  const Real t23 = x*z;
  const Real t24 = y*z;
  const Real t25 = t12*t8;
  const Real t26 = (1.0/2500.0)*t18;
  const Real t27 = t26*(-t0*t22*y + 80*t0*y*z + 10*t12*y*z + 25*t21*y - t23*t5 - t23*t7 - t24*t25 + 4*t4*t6*x*z + 50*t6*x - 250*x);
  const Real t28 = 10*t12;
  const Real t29 = t26*(t0*t28 + 160*t0*t3 - 300*t0 + 50*t10 + 4*t14*t16 - 120*t16*t6 - t25*t3 + t28*t3 - 300*t3 + 175*z - 750);
  const Real t30 = 50*t6;
  const Real t31 = t12*t16;
  const Real t32 = t26*(-t12*t23*t9 + t14*t20*y + 25*t21*x - t22*t3*x + t23*t28 + t24*t5 - t24*t7 + 80*t3*x*z + t30*y + 250*y);
  const Real t33 = pow(y, 3);
  oracle.second[0][0] = t19*(2*t0*t4*t6 - t0*t5 - t0*t7 + 450*t0 - t1 - t13*t2*y - t17 + 80*t2*y + 525);
  oracle.second[0][1] = t27;
  oracle.second[0][2] = t29;
  oracle.second[1][0] = t27;
  oracle.second[1][1] = t19*(t11*t14 - t11*t31 - t15 - t16*t22*z + 50*t16 + t30*z + 5*t31);
  oracle.second[1][2] = t32;
  oracle.second[2][0] = t29;
  oracle.second[2][1] = t32;
  oracle.second[2][2] = t19*(t1 - t13*t33*x - t17 + 2*t3*t4*t6 + 20*t3*t4 - t3*t7 - 450*t3 + 80*t33*x - 525);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle2(const Real x, const Real y, const Real z,
                           TensorOracle &oracle) {
  EvaluateTensorOracle2First(x, y, z, oracle);
  EvaluateTensorOracle2Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle3First(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = (1.0/25.0)*z;
  const Real t1 = pow(x, 2);
  const Real t2 = pow(y, 2);
  const Real t3 = exp(-1.0/5.0*t1 - 1.0/5.0*t2 - 1.0/5.0*pow(z, 2));
  const Real t4 = (1.0/50.0)*t1 + (1.0/50.0)*t2;
  const Real t5 = (2.0/5.0)*t3*((2.0/25.0)*t1 + (2.0/25.0)*t2 - t4*z - 11.0/100.0*z + 9.0/10.0);
  oracle.first[0] = t3*(-t0*x + (4.0/25.0)*x) - t5*x;
  oracle.first[1] = t3*(-t4 - 11.0/100.0) - t5*z;
  oracle.first[2] = t3*(-t0*y + (4.0/25.0)*y) - t5*y;
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle3Second(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = 2*t0;
  const Real t2 = pow(y, 2);
  const Real t3 = 2*z;
  const Real t4 = 8*t0 + 8*t2 - t3*(t0 + t2);
  const Real t5 = t4 - 11*z + 90;
  const Real t6 = z - 4;
  const Real t7 = 40*t6;
  const Real t8 = 200 - 50*z;
  const Real t9 = pow(z, 2);
  const Real t10 = exp(-1.0/5.0*t0 - 1.0/5.0*t2 - 1.0/5.0*t9);
  const Real t11 = (1.0/1250.0)*t10;
  const Real t12 = t11*(10*t0 + 10*t2 + t3*t5 + 20*t6*z + 5);
  const Real t13 = t12*x;
  const Real t14 = (1.0/625.0)*t10*x*y*(t4 + 9*z + 10);
  const Real t15 = 2*t2;
  const Real t16 = t12*y;
  oracle.second[0][0] = t11*(t0*t7 + t5*(t1 - 5) + t8);
  oracle.second[0][1] = t13;
  oracle.second[0][2] = t14;
  oracle.second[1][0] = t13;
  oracle.second[1][1] = t11*(t5*(2*t9 - 5) + 10*z*(t1 + t15 + 11));
  oracle.second[1][2] = t16;
  oracle.second[2][0] = t14;
  oracle.second[2][1] = t16;
  oracle.second[2][2] = t11*(t2*t7 + t5*(t15 - 5) + t8);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle3(const Real x, const Real y, const Real z,
                           TensorOracle &oracle) {
  EvaluateTensorOracle3First(x, y, z, oracle);
  EvaluateTensorOracle3Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle4First(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*pow(z, 2));
  const Real t3 = (3.0/50.0)*t2;
  const Real t4 = -3.0/100.0*t0 - 3.0/100.0*t1 + (1.0/25.0)*z + 7.0/50.0;
  const Real t5 = x*y;
  const Real t6 = (1.0/50.0)*t0 + (1.0/50.0)*t1 + (9.0/100.0)*z - 17.0/100.0;
  const Real t7 = (2.0/5.0)*t2*t6;
  const Real t8 = (2.0/5.0)*t2*t4;
  oracle.first[0] = -t0*t3 - t0*t8 + t2*t4 + (1.0/25.0)*t2*x*y - t5*t7;
  oracle.first[1] = (1.0/25.0)*t2*x + (9.0/100.0)*t2*y - t7*y*z - t8*x*z;
  oracle.first[2] = (1.0/25.0)*t1*t2 - t1*t7 + t2*t6 - t3*t5 - t5*t8;
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle4Second(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 3);
  const Real t1 = pow(x, 2);
  const Real t2 = 4*z;
  const Real t3 = pow(y, 2);
  const Real t4 = 3*t1 - t2 + 3*t3 - 14;
  const Real t5 = 2*t1;
  const Real t6 = 2*t3;
  const Real t7 = t5 + t6 + 9*z - 17;
  const Real t8 = 5*t7;
  const Real t9 = t8*y;
  const Real t10 = 2*t4;
  const Real t11 = pow(z, 2);
  const Real t12 = exp(-1.0/5.0*t1 - 1.0/5.0*t11 - 1.0/5.0*t3);
  const Real t13 = (1.0/1250.0)*t12;
  const Real t14 = x*y;
  const Real t15 = t4*t5;
  const Real t16 = t13*(30*t1*z - 20*t1 - 20*t14*z - 45*t14 - t15*z + 5*t4*z + 2*t7*x*y*z + 50);
  const Real t17 = 40*x;
  const Real t18 = t13*(60*t1*y - t15*y - t17*t3 + 2*t3*t7*x + 5*t4*y - t8*x + 50*x - 75*y);
  const Real t19 = -5*t4*x;
  const Real t20 = t4*x;
  const Real t21 = (1.0/2500.0)*t12*(-40*t14 - t2*t20*y + 4*t3*t7*z - 40*t3*z - 90*t3 - 10*t7*z + 60*x*y*z + 225);
  const Real t22 = pow(y, 3);
  oracle.second[0][0] = t13*(-t0*t10 + 60*t0 + 2*t1*t7*y - 40*t1*y + 15*t4*x - t9 - 225*x + 50*y);
  oracle.second[0][1] = t16;
  oracle.second[0][2] = t18;
  oracle.second[1][0] = t16;
  oracle.second[1][1] = t13*(-t10*t11*x + 2*t11*t7*y - t17*z - t19 - t9 - 90*y*z);
  oracle.second[1][2] = t21;
  oracle.second[2][0] = t18;
  oracle.second[2][1] = t21;
  oracle.second[2][2] = t13*(-t19 - t20*t6 + 2*t22*t7 - 40*t22 + 60*t3*x - 15*t7*y - 75*x + 150*y);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle4(const Real x, const Real y, const Real z,
                           TensorOracle &oracle) {
  EvaluateTensorOracle4First(x, y, z, oracle);
  EvaluateTensorOracle4Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle5First(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t4 = t1*t3;
  const Real t5 = t4*x;
  const Real t6 = (1.0/50.0)*t0 + (1.0/50.0)*t1 + (6.0/125.0)*z + 11.0/25.0;
  const Real t7 = (3.0/100.0)*t0 + (3.0/100.0)*t1 - 1.0/20.0*z + 21.0/100.0;
  const Real t8 = t3*y;
  const Real t9 = (4.0/5.0)*t7;
  const Real t10 = t8*t9;
  const Real t11 = -1.0/25.0*t0 - 1.0/25.0*t1 + (1.0/50.0)*t2 + (7.0/100.0)*z - 3.0/10.0;
  const Real t12 = (2.0/5.0)*t11;
  const Real t13 = t3*pow(y, 3);
  oracle.first[0] = -t0*t10 + (3.0/25.0)*t0*t3*y - t12*t5 - t3*t6*x + 2*t3*t7*y + (1.0/10.0)*t3*x - 2.0/25.0*t5;
  oracle.first[1] = t1*t3*((1.0/25.0)*z + 7.0/100.0) - t10*x*z - t12*t4*z - t3*t6*z - 1.0/10.0*t3*x*y + (3.0/25.0)*t3;
  oracle.first[2] = (3.0/25.0)*t1*t3*x + 2*t11*t3*y - t12*t13 - 2.0/25.0*t13 + 2*t3*t7*x + (1.0/10.0)*t3*y - t5*t9 - t6*t8;
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle5Second(const Real x, const Real y, const Real z,
                TensorOracle &oracle) {
  const Real t0 = 60*z;
  const Real t1 = pow(x, 2);
  const Real t2 = 125*t1;
  const Real t3 = pow(y, 2);
  const Real t4 = pow(x, 3);
  const Real t5 = 3*t1 + 3*t3 - 5*z + 21;
  const Real t6 = x*y;
  const Real t7 = 30*t5*t6;
  const Real t8 = 5*t3;
  const Real t9 = 5*t1 + t8 + 12*z + 110;
  const Real t10 = 4*t1;
  const Real t11 = pow(z, 2);
  const Real t12 = 2*t11;
  const Real t13 = t10 - t12 + 4*t3 - 7*z + 30;
  const Real t14 = -5*t13*t3;
  const Real t15 = t1*t3;
  const Real t16 = 2*t13;
  const Real t17 = (1.0/1250.0)*exp(-1.0/5.0*t1 - 1.0/5.0*t11 - 1.0/5.0*t3);
  const Real t18 = 50*z;
  const Real t19 = 4*z + 7;
  const Real t20 = 10*t5;
  const Real t21 = t20*z;
  const Real t22 = t3*x;
  const Real t23 = t16*z;
  const Real t24 = t17*(-t0*t1*y + 4*t1*t5*y*z + 50*t1*y - t18*x - t19*t8*x - t21*y - t22*t23 + 40*t3*x*z + 2*t9*x*z - 60*x - 125*y);
  const Real t25 = pow(y, 3);
  const Real t26 = t25*x;
  const Real t27 = 2*t9;
  const Real t28 = t17*(-t1*t20 + 225*t1 + t10*t3*t5 + 10*t13*t6 - 120*t15 - t16*t26 - t20*t3 + 80*t26 + t27*t6 + 225*t3 - 300*t6 - 125*z + 525);
  const Real t29 = t17*(-t0*t22 + 10*t13*y*z - t18*y - 5*t19*t25 + 25*t19*y - t21*x - t23*t25 + 40*t25*z + 4*t3*t5*x*z + 50*t3*x + 2*t9*y*z - 125*x - 60*y);
  const Real t30 = pow(y, 4);
  oracle.second[0][0] = t17*(-t0 + 80*t1*t3 + 2*t1*t9 - t14 - t15*t16 - t2 - 125*t3 + 4*t4*t5*y - 120*t4*y - t7 + 450*x*y - 425);
  oracle.second[0][1] = t24;
  oracle.second[0][2] = t28;
  oracle.second[1][0] = t24;
  oracle.second[1][1] = t17*(-25*t1 + 4*t11*t5*x*y + 2*t11*t9 - t12*t13*t3 - t14 - 10*t19*t3*z - t20*t6 + 25*t3 + 100*x*y*z - 180*z - 550);
  oracle.second[1][2] = t29;
  oracle.second[2][0] = t28;
  oracle.second[2][1] = t29;
  oracle.second[2][2] = t17*(50*t11 + 25*t13*t3 - t16*t30 - t2 + 4*t26*t5 - 120*t26 + t27*t3 - 725*t3 + 80*t30 + 450*t6 - t7 + 115*z - 1175);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle5(const Real x, const Real y, const Real z,
                           TensorOracle &oracle) {
  EvaluateTensorOracle5First(x, y, z, oracle);
  EvaluateTensorOracle5Second(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateTensorOracle(const int component, const Real x, const Real y,
                          const Real z, TensorOracle &oracle) {
  if (component == 0) EvaluateTensorOracle0(x, y, z, oracle);
  if (component == 1) EvaluateTensorOracle1(x, y, z, oracle);
  if (component == 2) EvaluateTensorOracle2(x, y, z, oracle);
  if (component == 3) EvaluateTensorOracle3(x, y, z, oracle);
  if (component == 4) EvaluateTensorOracle4(x, y, z, oracle);
  if (component == 5) EvaluateTensorOracle5(x, y, z, oracle);
}

KOKKOS_INLINE_FUNCTION
void EvaluateAnalyticOracle(const Real x, const Real y, const Real z,
                            AnalyticOracle &oracle) {
  const Real t0 = pow(x, 2);
  const Real t1 = pow(y, 2);
  const Real t2 = pow(z, 2);
  const Real t3 = exp(-1.0/5.0*t0 - 1.0/5.0*t1 - 1.0/5.0*t2);
  const Real t4 = pow(z, 3);
  const Real t5 = (7.0/100.0)*t0 + (7.0/100.0)*t1;
  const Real t6 = t3*((11.0/100.0)*t0 + (11.0/100.0)*t1 + (3.0/100.0)*t4 - t5*z + (17.0/100.0)*z + 1);
  const Real t7 = (7.0/50.0)*z;
  const Real t8 = (2.0/5.0)*t6;
  const Real t9 = (2.0/5.0)*z;
  const Real t10 = 7*z;
  const Real t11 = t10 - 11;
  const Real t12 = 4*t0;
  const Real t13 = 2*t0;
  const Real t14 = t13 - 5;
  const Real t15 = t0 + t1;
  const Real t16 = 11*t0 + 11*t1 - t10*t15 + 3*t4 + 17*z + 100;
  const Real t17 = (1.0/5.0)*t16;
  const Real t18 = 55 - 35*z;
  const Real t19 = (1.0/250.0)*t3;
  const Real t20 = 2*z;
  const Real t21 = 7*t0 + 7*t1;
  const Real t22 = -9*t2 + t21;
  const Real t23 = t19*(t11*t20 + t16*t9 + t22 - 52);
  const Real t24 = t23*x;
  const Real t25 = t3*x;
  const Real t26 = t25*y;
  const Real t27 = (1.0/125.0)*t26*((11.0/5.0)*t0 + (11.0/5.0)*t1 - 7.0/5.0*t15*z + (3.0/5.0)*t4 + (87.0/5.0)*z - 2);
  const Real t28 = 2*t2;
  const Real t29 = t28 - 5;
  const Real t30 = t23*y;
  const Real t31 = 4*t1;
  const Real t32 = 2*t1;
  const Real t33 = t32 - 5;
  const Real t34 = t3*((9.0/100.0)*t0 + (9.0/100.0)*t1 - 1.0/25.0*t2 + (13.0/100.0)*z + 7.0/10.0);
  const Real t35 = t34*x;
  const Real t36 = (2.0/25.0)*z;
  const Real t37 = (1.0/50.0)*t2 - t36 + t5 + 3.0/10.0;
  const Real t38 = t3*t37;
  const Real t39 = t38*y;
  const Real t40 = (7.0/50.0)*t26;
  const Real t41 = t0*t3;
  const Real t42 = (2.0/5.0)*t39*x;
  const Real t43 = (2.0/5.0)*t0;
  const Real t44 = (1.0/25.0)*z;
  const Real t45 = t44 - 2.0/25.0;
  const Real t46 = t3*y;
  const Real t47 = 13.0/100.0 - t36;
  const Real t48 = t1*t3;
  const Real t49 = (2.0/5.0)*y;
  const Real t50 = t35*t49;
  const Real t51 = 175*y;
  const Real t52 = pow(x, 3);
  const Real t53 = t0*y;
  const Real t54 = 140*t53;
  const Real t55 = 4*t2;
  const Real t56 = 9*t0 + 9*t1 - t55 + 13*z + 70;
  const Real t57 = t56*x;
  const Real t58 = 8*z;
  const Real t59 = t21 + t28 - t58 + 30;
  const Real t60 = 5*y;
  const Real t61 = t59*t60;
  const Real t62 = 2*t52;
  const Real t63 = t13*y;
  const Real t64 = t59*t63;
  const Real t65 = (1.0/1250.0)*t3;
  const Real t66 = 200*z;
  const Real t67 = 180*z;
  const Real t68 = 10*z;
  const Real t69 = t56*t68;
  const Real t70 = t58 - 13;
  const Real t71 = 10*t0;
  const Real t72 = z - 2;
  const Real t73 = x*y;
  const Real t74 = 40*t73;
  const Real t75 = t59*x;
  const Real t76 = 4*z;
  const Real t77 = t76*y;
  const Real t78 = t72*t74 + 140*t73*z - t75*t77;
  const Real t79 = (1.0/2500.0)*t3;
  const Real t80 = t79*(-t0*t67 + t12*t56*z - t66 - t69 + t70*t71 + t78 + 325);
  const Real t81 = 175*x;
  const Real t82 = 5*t75;
  const Real t83 = t1*x;
  const Real t84 = 140*t83;
  const Real t85 = t32*t75;
  const Real t86 = 225*y;
  const Real t87 = -t56*t60;
  const Real t88 = -180*t53 + t56*t63 + t86 + t87;
  const Real t89 = t65*(-t81 + t82 + t84 - t85 + t88);
  const Real t90 = 100*x;
  const Real t91 = 50*y;
  const Real t92 = -t91;
  const Real t93 = 40*z;
  const Real t94 = t93*y;
  const Real t95 = t70*x;
  const Real t96 = -5*t57;
  const Real t97 = t28*y;
  const Real t98 = 20*t1;
  const Real t99 = 70*z;
  const Real t100 = 90*z;
  const Real t101 = t100*t73;
  const Real t102 = 50*z;
  const Real t103 = -t102;
  const Real t104 = 5*z;
  const Real t105 = t103 + t104*t59 + 100;
  const Real t106 = t65*(t1*t99 - t101 + t105 + t20*t57*y - t32*t59*z + t60*t95 + t72*t98);
  const Real t107 = pow(y, 3);
  const Real t108 = 2*t107;
  const Real t109 = 15*y;
  const Real t110 = 225*x;
  const Real t111 = t110 + t32*t57 - 180*t83 + t96;
  const Real t112 = (3.0/50.0)*t0;
  const Real t113 = (3.0/50.0)*t1;
  const Real t114 = (1.0/20.0)*t0 + (1.0/20.0)*t1;
  const Real t115 = t3*(-t112 - t113 + t114*z + (19.0/100.0)*z - 1.0/5.0);
  const Real t116 = (3.0/25.0)*x;
  const Real t117 = (1.0/10.0)*z;
  const Real t118 = (2.0/5.0)*t115;
  const Real t119 = (3.0/25.0)*y;
  const Real t120 = 6*t0 + 6*t1 - t104*t15;
  const Real t121 = t120 - 19*z + 20;
  const Real t122 = t104 - 6;
  const Real t123 = 20*t0;
  const Real t124 = 125*z;
  const Real t125 = -t124;
  const Real t126 = t125 + 150;
  const Real t127 = 25*t0;
  const Real t128 = 25*t1;
  const Real t129 = -1.0/1250.0*t121*t20 - 1.0/1250.0*t122*t68 - 1.0/1250.0*t127 - 1.0/1250.0*t128 + 3.0/125.0;
  const Real t130 = t129*t25;
  const Real t131 = (1.0/625.0)*t26;
  const Real t132 = -t131*(t120 + 31*z - 40);
  const Real t133 = 5*t0;
  const Real t134 = 5*t1;
  const Real t135 = t133 + t134;
  const Real t136 = t129*t46;
  const Real t137 = t38*x;
  const Real t138 = t34*y;
  const Real t139 = (2.0/5.0)*t1;
  const Real t140 = t65*(2*t0*t59*z - t0*t99 - t101 - t105 - t123*t72 + 2*t56*x*y*z + 5*t70*x*y);
  const Real t141 = t65*(t111 + t51 - t54 - t61 + t64);
  const Real t142 = 50*x;
  const Real t143 = t93*x;
  const Real t144 = t68*y;
  const Real t145 = -t82;
  const Real t146 = t79*(4*t1*t56*z - t1*t67 + 10*t1*t70 - t66 - t69 - t78 + 325);
  const Real t147 = t3*(t114 + (3.0/25.0)*z + 11.0/10.0);
  const Real t148 = (3.0/100.0)*t0 + (3.0/100.0)*t1;
  const Real t149 = t148 - 1.0/20.0*z + 21.0/100.0;
  const Real t150 = 2*t149;
  const Real t151 = t150*t26;
  const Real t152 = (1.0/25.0)*t0;
  const Real t153 = -1.0/25.0*t1 - t152 + (1.0/50.0)*t2 + (7.0/100.0)*z - 3.0/10.0;
  const Real t154 = t153*t41;
  const Real t155 = t150*t46;
  const Real t156 = (2.0/25.0)*t3;
  const Real t157 = (2.0/5.0)*t153*t3;
  const Real t158 = t119*t41;
  const Real t159 = (4.0/5.0)*t149;
  const Real t160 = t159*t41*y;
  const Real t161 = (2.0/5.0)*t147;
  const Real t162 = t161*x - 1.0/10.0*t3*x;
  const Real t163 = t44 + 7.0/100.0;
  const Real t164 = t147*t9;
  const Real t165 = t159*t26*z + (1.0/10.0)*t25*y;
  const Real t166 = t150*t25;
  const Real t167 = t116*t48;
  const Real t168 = t1*t159*t25;
  const Real t169 = (2.0/25.0)*t0;
  const Real t170 = t154*t49 + t169*t46;
  const Real t171 = t161*y - 1.0/10.0*t3*y;
  const Real t172 = 125*t1;
  const Real t173 = pow(x, 4);
  const Real t174 = -t10 + t12 - t28 + t31 + 30;
  const Real t175 = 2*t174;
  const Real t176 = t135 + 12*z + 110;
  const Real t177 = 450*t73;
  const Real t178 = t52*y;
  const Real t179 = 3*t0 + 3*t1;
  const Real t180 = -t104 + t179 + 21;
  const Real t181 = 4*t180;
  const Real t182 = t180*t73;
  const Real t183 = 30*t182;
  const Real t184 = -t177 - t178*t181 + 120*t178 + t183;
  const Real t185 = 50*t2;
  const Real t186 = t185 + 115*z - 1175;
  const Real t187 = 60*x;
  const Real t188 = t102*x;
  const Real t189 = t76 + 7;
  const Real t190 = 5*t189;
  const Real t191 = 40*t52;
  const Real t192 = t174*t20;
  const Real t193 = t68*x;
  const Real t194 = t174*t193 + 25*t189*x;
  const Real t195 = 60*y;
  const Real t196 = t0*t195;
  const Real t197 = y*z;
  const Real t198 = -t0*t91 - t12*t180*t197 + t144*t180 + t196*z + 125*y;
  const Real t199 = t65*(t176*t20*x - t187 - t188 - t190*t52 + t191*z - t192*t52 + t194 + t198);
  const Real t200 = 225*t0;
  const Real t201 = 225*t1;
  const Real t202 = t180*t71;
  const Real t203 = 10*t1;
  const Real t204 = t180*t203;
  const Real t205 = t0*t1;
  const Real t206 = 120*t205;
  const Real t207 = t1*t12;
  const Real t208 = t180*t207;
  const Real t209 = t174*y;
  const Real t210 = t209*t62;
  const Real t211 = t124 - 525;
  const Real t212 = 300*t73;
  const Real t213 = t174*t73;
  const Real t214 = 2*t176*t73 - t212 + 10*t213;
  const Real t215 = t65*(80*t178 - t200 - t201 + t202 + t204 + t206 - t208 - t210 + t211 + t214);
  const Real t216 = -5*t0*t174;
  const Real t217 = 10*t182;
  const Real t218 = t13*t174;
  const Real t219 = t189*t71;
  const Real t220 = t197*t90;
  const Real t221 = t182*t55;
  const Real t222 = -2*t176*t2 + t67 + 550;
  const Real t223 = 125*x;
  const Real t224 = t1*t142;
  const Real t225 = t1*t187;
  const Real t226 = t225*z;
  const Real t227 = t180*t193;
  const Real t228 = t31*z;
  const Real t229 = t180*t228*x;
  const Real t230 = -2*t176*y*z + t195 + t91*z;
  const Real t231 = t65*(40*t0*y*z - t133*t189*y - t174*t63*z + t223 - t224 + t226 + t227 - t229 - t230);
  const Real t232 = t107*x;
  const Real t233 = t177 + t181*t232 - t183 - 120*t232;
  const Real t234 = 125*t0;
  const Real t235 = -80*t0*t1 + t1*t218 + t172 + t234 + 60*z + 425;
  const Real t236 = (1.0/50.0)*t0 + (1.0/50.0)*t1;
  const Real t237 = t236 + (9.0/100.0)*z - 17.0/100.0;
  const Real t238 = t237*t3;
  const Real t239 = t238*x;
  const Real t240 = -t148 + (1.0/25.0)*z + 7.0/50.0;
  const Real t241 = t240*t3;
  const Real t242 = (2.0/5.0)*t73;
  const Real t243 = t241*t242 + (3.0/50.0)*t26;
  const Real t244 = -t241;
  const Real t245 = t238*t242;
  const Real t246 = 9*z;
  const Real t247 = t13 + t32;
  const Real t248 = t246 + t247 - 17;
  const Real t249 = t248*x;
  const Real t250 = t179 - t76 - 14;
  const Real t251 = -t250*t60;
  const Real t252 = -t196 + t250*t63 + t251 + 75*y;
  const Real t253 = t248*t68;
  const Real t254 = -t187*t197 + t250*t73*t76 + t74;
  const Real t255 = t79*(-t0*t93 - 90*t0 + t12*t248*z - t253 + t254 + 225);
  const Real t256 = 40*t53;
  const Real t257 = t248*t60;
  const Real t258 = t250*x;
  const Real t259 = -5*t258;
  const Real t260 = -t225 + t258*t32 + t259 + 75*x;
  const Real t261 = t65*(t248*t63 - t256 - t257 + t260 + t91);
  const Real t262 = 5*t249;
  const Real t263 = -t262;
  const Real t264 = t104*t250;
  const Real t265 = 20*z;
  const Real t266 = -2*t248*x*y*z + t265*t73 + 45*t73;
  const Real t267 = t65*(2*t1*t250*z - 30*t1*z + 20*t1 - t264 - t266 - 50);
  const Real t268 = 40*t83;
  const Real t269 = t153*t25;
  const Real t270 = t269*y;
  const Real t271 = t0 - t1;
  const Real t272 = t271*t3;
  const Real t273 = t149*t272;
  const Real t274 = -t166;
  const Real t275 = (2.0/5.0)*t149*t271;
  const Real t276 = (2.0/25.0)*t1;
  const Real t277 = t139*t269 + t25*t276;
  const Real t278 = 60*t271;
  const Real t279 = t180*t271;
  const Real t280 = 5*t279;
  const Real t281 = -15*t174*x*y + t212 + t280;
  const Real t282 = t180*t265;
  const Real t283 = t271*z;
  const Real t284 = -10*t174*y*z - 25*t189*y;
  const Real t285 = t79*(80*t0*y*z - t12*t209*z + 4*t180*t271*x*z - t187*t283 - t219*y + 50*t271*x - t282*x - t284 - 250*x);
  const Real t286 = t79*(-300*t0 - 300*t1 + t174*t203 - t174*t207 + t174*t71 + t185 + 160*t205 - 120*t271*t73 + 4*t279*t73 + 175*z - 750);
  const Real t287 = t174*x;
  const Real t288 = t189*x;
  const Real t289 = t79*(t194 - t195*t283 - t203*t288 - t228*t287 + t271*t91 + t279*t77 + t282*y + 80*t83*z + 250*y);
  const Real t290 = t108*t287;
  const Real t291 = t125 + 525;
  const Real t292 = t3*(t169 - t236*z + t276 - 11.0/100.0*z + 9.0/10.0);
  const Real t293 = (2.0/5.0)*t292;
  const Real t294 = 8*t0 + 8*t1 - t15*t20;
  const Real t295 = t294 - 11*z + 90;
  const Real t296 = z - 4;
  const Real t297 = 40*t296;
  const Real t298 = t103 + 200;
  const Real t299 = (1.0/1250.0)*t20*t295 + (1.0/1250.0)*t203 + (1.0/1250.0)*t265*t296 + (1.0/1250.0)*t71 + 1.0/250.0;
  const Real t300 = t25*t299;
  const Real t301 = t131*(t246 + t294 + 10);
  const Real t302 = t299*t46;
  const Real t303 = t241*x;
  const Real t304 = t238*y;
  const Real t305 = t65*(30*t0*z - t123 - t13*t250*z + t264 - t266 + 50);
  const Real t306 = t65*(2*t1*t248*x - t252 - t262 - t268 + 50*x);
  const Real t307 = t79*(4*t1*t248*z - t1*t93 - 90*t1 - t253 - t254 + 225);
  const Real t308 = t153*t48;
  const Real t309 = -5*t1*t174;
  const Real t310 = t65*(40*t1*x*z - t134*t288 + 2*t176*x*z - t187 - t188 - t198 - t287*t32*z);
  const Real t311 = t65*(t200 + t201 - t202 - t204 - t206 + t208 + t214 + 80*t232 - t290 + t291);
  const Real t312 = t65*(-t107*t190 - t107*t192 + 40*t107*z - t223 + t224 - t226 - t227 + t229 - t230 - t284);
  const Real t313 = pow(y, 4);
  oracle.scalar = t6;
  oracle.scalar_first[0] = t3*(-t7*x + (11.0/50.0)*x) - t8*x;
  oracle.scalar_first[1] = t3*((9.0/100.0)*t2 - t5 + 17.0/100.0) - t6*t9;
  oracle.scalar_first[2] = t3*(-t7*y + (11.0/50.0)*y) - t8*y;
  oracle.scalar_second[0][0] = t19*(t11*t12 + t14*t17 + t18);
  oracle.scalar_second[0][1] = t24;
  oracle.scalar_second[0][2] = t27;
  oracle.scalar_second[1][0] = t24;
  oracle.scalar_second[1][1] = t19*(t17*t29 + t20*(t22 - 17) + 45*z);
  oracle.scalar_second[1][2] = t30;
  oracle.scalar_second[2][0] = t27;
  oracle.scalar_second[2][1] = t30;
  oracle.scalar_second[2][2] = t19*(t11*t31 + t17*t33 + t18);
  oracle.vector[0] = t35 - t39;
  oracle.vector_first[0][0] = -t34*t43 + t34 - t40 + (9.0/50.0)*t41 + t42;
  oracle.vector_first[0][1] = (2.0/5.0)*t3*t37*y*z + t3*t47*x - t35*t9 - t45*t46;
  oracle.vector_first[0][2] = (2.0/5.0)*t1*t3*t37 + (9.0/50.0)*t3*x*y - t38 - 7.0/50.0*t48 - t50;
  oracle.vector_second[0][0][0] = t65*(-t51 - 180*t52 + t54 + t56*t62 - 15*t57 + t61 - t64 + 675*x);
  oracle.vector_second[0][0][1] = t80;
  oracle.vector_second[0][0][2] = t89;
  oracle.vector_second[0][1][0] = t80;
  oracle.vector_second[0][1][1] = t65*(t28*t57 - t59*t97 + t61 + t68*t95 + t72*t94 - t90 + t92 + t96);
  oracle.vector_second[0][1][2] = t106;
  oracle.vector_second[0][2][0] = t89;
  oracle.vector_second[0][2][1] = t106;
  oracle.vector_second[0][2][2] = t65*(140*t107 - t108*t59 + t109*t59 + t111 - 525*y);
  oracle.vector[1] = t115;
  oracle.vector_first[1][0] = -t118*x + t3*(-t116 + t117*x);
  oracle.vector_first[1][1] = -t115*t9 + t3*(t114 + 19.0/100.0);
  oracle.vector_first[1][2] = -t118*y + t3*(t117*y - t119);
  oracle.vector_second[1][0][0] = t65*(-t121*t14 - t122*t123 - t126);
  oracle.vector_second[1][0][1] = t130;
  oracle.vector_second[1][0][2] = t132;
  oracle.vector_second[1][1][0] = t130;
  oracle.vector_second[1][1][1] = -t65*(t121*t29 + t68*(t135 + 19));
  oracle.vector_second[1][1][2] = t136;
  oracle.vector_second[1][2][0] = t132;
  oracle.vector_second[1][2][1] = t136;
  oracle.vector_second[1][2][2] = t65*(-t121*t33 - t122*t98 - t126);
  oracle.vector[2] = t137 + t138;
  oracle.vector_first[2][0] = (9.0/50.0)*t26 - t38*t43 + t38 + (7.0/50.0)*t41 - t50;
  oracle.vector_first[2][1] = -t137*t9 - t138*t9 + t3*t45*x + t3*t47*y;
  oracle.vector_first[2][2] = -t139*t34 + t34 + t40 - t42 + (9.0/50.0)*t48;
  oracle.vector_second[2][0][0] = t65*(-140*t52 + t59*t62 - 15*t75 + t88 + 525*x);
  oracle.vector_second[2][0][1] = t140;
  oracle.vector_second[2][0][2] = t141;
  oracle.vector_second[2][1][0] = t140;
  oracle.vector_second[2][1][1] = t65*(t142 - t143*t72 + t144*t70 + t145 + t28*t75 + t56*t97 + t87 - 100*y);
  oracle.vector_second[2][1][2] = t146;
  oracle.vector_second[2][2][0] = t141;
  oracle.vector_second[2][2][1] = t146;
  oracle.vector_second[2][2][2] = t65*(-180*t107 + t108*t56 - t109*t56 + t145 + t81 - t84 + t85 + 675*y);
  oracle.tensor[0] = t147 - t151 + t154;
  oracle.tensor_first[0][0] = 2*t153*t3*x - t155 - t156*t52 - t157*t52 - t158 + t160 - t162;
  oracle.tensor_first[0][1] = -t154*t9 + t163*t41 - t164 + t165 + (3.0/25.0)*t3;
  oracle.tensor_first[0][2] = -t166 - t167 + t168 - t170 - t171;
  oracle.tensor_second[0][0][0] = t65*(-725*t0 + t127*t174 + t13*t176 - t172 - t173*t175 + 80*t173 + t184 + t186);
  oracle.tensor_second[0][0][1] = t199;
  oracle.tensor_second[0][0][2] = t215;
  oracle.tensor_second[0][1][0] = t199;
  oracle.tensor_second[0][1][1] = t65*(t127 - t128 - t2*t218 - t216 + t217 - t219*z - t220 - t221 - t222);
  oracle.tensor_second[0][1][2] = t231;
  oracle.tensor_second[0][2][0] = t215;
  oracle.tensor_second[0][2][1] = t231;
  oracle.tensor_second[0][2][2] = t65*(2*t1*t176 - t216 - t233 - t235);
  oracle.tensor[1] = t239 - t241*y;
  oracle.tensor_first[1][0] = t152*t3 - t238*t43 + t238 + t243;
  oracle.tensor_first[1][1] = -t239*t9 + (2.0/5.0)*t240*t3*y*z + (9.0/100.0)*t3*x - 1.0/25.0*t46;
  oracle.tensor_first[1][2] = t113*t3 + t139*t241 + t244 - t245 + (1.0/25.0)*t25*y;
  oracle.tensor_second[1][0][0] = t65*(-t191 + t248*t62 - 15*t249 + t252 + 150*x);
  oracle.tensor_second[1][0][1] = t255;
  oracle.tensor_second[1][0][2] = t261;
  oracle.tensor_second[1][1][0] = t255;
  oracle.tensor_second[1][1][1] = t65*(-t100*x + t249*t28 + t250*t97 + t251 + t263 + t94);
  oracle.tensor_second[1][1][2] = t267;
  oracle.tensor_second[1][2][0] = t261;
  oracle.tensor_second[1][2][1] = t267;
  oracle.tensor_second[1][2][2] = t65*(-60*t107 + t108*t250 - t109*t250 + t142 + t249*t32 + t263 - t268 + t86);
  oracle.tensor[2] = t270 + t273;
  oracle.tensor_first[2][0] = t153*t3*y - t170 - t25*t275 + (3.0/50.0)*t271*t3*x - t274;
  oracle.tensor_first[2][1] = t163*t3*x*y - t270*t9 - 1.0/20.0*t272 - t273*t9;
  oracle.tensor_first[2][2] = t153*t3*x - t155 + (3.0/50.0)*t271*t3*y - t275*t46 - t277;
  oracle.tensor_second[2][0][0] = t65*(2*t0*t180*t271 - t0*t278 + 450*t0 - t123*t180 - t210 - t211 - t281 + 80*t52*y);
  oracle.tensor_second[2][0][1] = t285;
  oracle.tensor_second[2][0][2] = t286;
  oracle.tensor_second[2][1][0] = t285;
  oracle.tensor_second[2][1][1] = t65*(t102*t271 - t189*t68*t73 - t213*t28 + t279*t28 - t280 + t287*t60 + t91*x);
  oracle.tensor_second[2][1][2] = t289;
  oracle.tensor_second[2][2][0] = t286;
  oracle.tensor_second[2][2][1] = t289;
  oracle.tensor_second[2][2][2] = t65*(2*t1*t180*t271 + 20*t1*t180 - t1*t278 - 450*t1 + 80*t107*x - t281 - t290 - t291);
  oracle.tensor[3] = t292;
  oracle.tensor_first[3][0] = -t293*x + t3*(-t44*x + (4.0/25.0)*x);
  oracle.tensor_first[3][1] = -t292*t9 + t3*(-t236 - 11.0/100.0);
  oracle.tensor_first[3][2] = -t293*y + t3*(-t44*y + (4.0/25.0)*y);
  oracle.tensor_second[3][0][0] = t65*(t0*t297 + t14*t295 + t298);
  oracle.tensor_second[3][0][1] = t300;
  oracle.tensor_second[3][0][2] = t301;
  oracle.tensor_second[3][1][0] = t300;
  oracle.tensor_second[3][1][1] = t65*(t29*t295 + t68*(t247 + 11));
  oracle.tensor_second[3][1][2] = t302;
  oracle.tensor_second[3][2][0] = t301;
  oracle.tensor_second[3][2][1] = t302;
  oracle.tensor_second[3][2][2] = t65*(t1*t297 + t295*t33 + t298);
  oracle.tensor[4] = t303 + t304;
  oracle.tensor_first[4][0] = -t112*t3 - t241*t43 - t244 - t245 + (1.0/25.0)*t3*x*y;
  oracle.tensor_first[4][1] = (1.0/25.0)*t3*x + (9.0/100.0)*t3*y - t303*t9 - t304*t9;
  oracle.tensor_first[4][2] = (1.0/25.0)*t1*t3 - t139*t238 + t237*t3 - t243;
  oracle.tensor_second[4][0][0] = t65*(2*t0*t248*y - t110 - t250*t62 + 15*t250*x - t256 - t257 + 60*t52 - t92);
  oracle.tensor_second[4][0][1] = t305;
  oracle.tensor_second[4][0][2] = t306;
  oracle.tensor_second[4][1][0] = t305;
  oracle.tensor_second[4][1][1] = t65*(-t100*y - t143 + 2*t2*t248*y - t257 - t258*t28 - t259);
  oracle.tensor_second[4][1][2] = t307;
  oracle.tensor_second[4][2][0] = t306;
  oracle.tensor_second[4][2][1] = t307;
  oracle.tensor_second[4][2][2] = t65*(2*t107*t248 - 40*t107 - t109*t248 - t260 + 150*y);
  oracle.tensor[5] = t147 + t151 + t308;
  oracle.tensor_first[5][0] = t155 + t158 - t160 - t162 - t277;
  oracle.tensor_first[5][1] = t1*t163*t3 - t164 - t165 + (3.0/25.0)*t3 - t308*t9;
  oracle.tensor_first[5][2] = -t107*t156 - t107*t157 + 2*t153*t3*y + t167 - t168 - t171 - t274;
  oracle.tensor_second[5][0][0] = t65*(2*t0*t176 - t184 - t235 - t309);
  oracle.tensor_second[5][0][1] = t310;
  oracle.tensor_second[5][0][2] = t311;
  oracle.tensor_second[5][1][0] = t310;
  oracle.tensor_second[5][1][1] = t65*(-t1*t174*t28 - t127 + t128 - t189*t203*z - t217 + t220 + t221 - t222 - t309);
  oracle.tensor_second[5][1][2] = t312;
  oracle.tensor_second[5][2][0] = t311;
  oracle.tensor_second[5][2][1] = t312;
  oracle.tensor_second[5][2][2] = t65*(-725*t1 + t128*t174 - t175*t313 + t176*t32 + t186 + t233 - t234 + 80*t313);
}

}  // namespace z4c_mms

#endif  // PGEN_UNIT_TESTS_Z4C_CARTOON_DERIVATIVES_ORACLE_HPP_
