#!/usr/bin/env bash
set -euo pipefail
bundle_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck disable=SC1091
source "${bundle_dir}/contract.env"

required=(
  EXPECTED_SOURCE_COMMIT EXPECTED_SOURCE_TREE EXPECTED_SOURCE_KOKKOS
  SOURCE_ROOT SOURCE_PATH EXECUTABLE EXPECTED_EXECUTABLE_SHA256
  BASELINE_ROOT BASELINE_CASE EXPECTED_BASELINE_ROOT_MANIFEST_SHA256
  EXPECTED_BASELINE_DETACHED_SHA256 EXPECTED_BASELINE_HISTORY_SHA256
  PRIOR_FIXED_ROOT PRIOR_FIXED_CASE EXPECTED_PRIOR_FIXED_ROOT_MANIFEST_SHA256
  EXPECTED_PRIOR_FIXED_DETACHED_SHA256 EXPECTED_PRIOR_FIXED_HISTORY_SHA256
  EXPECTED_PRIOR_FIXED_LOG_SHA256 EXPECTED_PRIOR_FIXED_COMMAND_SHA256
  PREDECESSOR_ROOT EXPECTED_PREDECESSOR_JOB_ID
  EXPECTED_PREDECESSOR_JOB_NAME EXPECTED_PREDECESSOR_BUNDLE_MANIFEST_SHA256
  EXPECTED_PREDECESSOR_PREFLIGHT_MANIFEST_SHA256 PREDECESSOR_CASE_KO002
  PREDECESSOR_CASE_KO05 PREDECESSOR_CASE_ZERO_SHIFT
  V1_ROOT EXPECTED_V1_JOB_ID EXPECTED_V1_JOB_NAME EXPECTED_V1_LEDGER_SHA256
  V3_INCOMPLETE_ROOT EXPECTED_V3_BUNDLE_MANIFEST_SHA256
  V4_ROOT EXPECTED_V4_BUNDLE_MANIFEST_SHA256
  EXPECTED_V4_PREFLIGHT_MANIFEST_SHA256
  V5_ROOT EXPECTED_V5_BUNDLE_MANIFEST_SHA256
  EXPECTED_V5_PREFLIGHT_MANIFEST_SHA256
  EXPECTED_V5_EMPTY_PREDECESSOR_LOG_SHA256
  V6_ROOT EXPECTED_V6_JOB_ID EXPECTED_V6_JOB_NAME
  EXPECTED_V6_ROOT_MANIFEST_SHA256 EXPECTED_V6_DETACHED_SHA256
  EXPECTED_V6_SACCT_SHA256 EXPECTED_V6_COMPARISON_SHA256
  EXPECTED_V6_FIXED_LOG_SHA256 EXPECTED_V6_ZERO_LOG_SHA256
  REMOTE_ROOT EXPECTED_JOB_NAME EXPECTED_ACCOUNT EXPECTED_NUMBERED_STEPS
  EXPECTED_RANKS EXPECTED_GPUS EXPECTED_GPU_NAME EXPECTED_NUM_LEVELS EXPECTED_MAX_REF_LEV
  EXPECTED_NMB_TOTAL_LIMIT EXPECTED_MAX_NMB_PER_RANK TARGET_TLIM
  CASE_KO05 CASE_ZERO_SHIFT_KO05
  INPUT_BASENAME EXPECTED_INPUT_SHA256 COEFFICIENT_BASENAME
  EXPECTED_COEFFICIENT_SHA256 EXPECTED_AMPLITUDE EXPECTED_ADM_MASS
  PROFILE_PATH EXPECTED_PROFILE_SHA256 PYTHON_BIN
)
for name in "${required[@]}"; do
  value=${!name:-}
  test -n "${value}"
  case "${value}" in
    *__UNSET__*|*__PLACEHOLDER__*)
      printf 'unbound contract field %s=%s\n' "${name}" "${value}" >&2
      exit 2
      ;;
  esac
done

test "${EXPECTED_NUMBERED_STEPS}" = 2
test "${EXPECTED_RANKS}" = 1
test "${EXPECTED_GPUS}" = 1
test "${EXPECTED_GPU_NAME}" = NVIDIA_A100-SXM4-80GB
test "${EXPECTED_NUM_LEVELS}" = 21
test "${EXPECTED_MAX_REF_LEV}" = 20
test "${EXPECTED_NMB_TOTAL_LIMIT}" = 16384
test "${EXPECTED_MAX_NMB_PER_RANK}" = 16384
test "${CASE_KO05}" != "${CASE_ZERO_SHIFT_KO05}"
test "${REMOTE_ROOT}" != "/"
test "${REMOTE_ROOT}" != "${HOME}"
test "${SOURCE_ROOT}" != "${REMOTE_ROOT}"
test "${PRIOR_FIXED_ROOT}" != "${REMOTE_ROOT}"
test "${PREDECESSOR_ROOT}" != "${REMOTE_ROOT}"
test "${V1_ROOT}" != "${REMOTE_ROOT}"
test "${V3_INCOMPLETE_ROOT}" != "${REMOTE_ROOT}"
test "${V4_ROOT}" != "${REMOTE_ROOT}"
test "${V5_ROOT}" != "${REMOTE_ROOT}"
test "${V6_ROOT}" != "${REMOTE_ROOT}"
