#!/usr/bin/env python3
"""Generate and verify the half-plane SO(2) direct-operator inventory."""

from __future__ import annotations

import argparse
from pathlib import Path

OPERATORS = (
    ("scalar `d_y`, active-suppressed mixed", "`F(s)`", "zero by SO(2)",
     "none", "`0`"),
    ("scalar `d_y^2`", "EvenScalar `F(s)`", "`2 F_s`", "centered `D_rho`",
     "`D_rho F/rho`"),
    ("vector `d_y V^rho`, `d_y V^y`", "OddLinear `V^rho=rho A`, `V^y=rho B`",
     "`-B`, `A`", "coefficient value", "`-V^y/rho`, `V^rho/rho`"),
    ("vector `d_y V^z`", "EvenScalar `C(s)`", "zero", "none", "`0`"),
    ("vector `d_y^2 V^z`", "EvenScalar `C(s)`", "`2 C_s`", "centered `D_rho`",
     "`D_rho V^z/rho`"),
    ("vector `d_y^2 V^rho`, `d_y^2 V^y`",
     "OddLinear `rho A(s)`, `rho B(s)`", "`2 rho A_s`, `2 rho B_s`",
     "centered `D_rho`", "`D_rho V/rho-V/rho^2`"),
    ("vector `d_rho d_y V^rho`, `d_rho d_y V^y`",
     "rotated OddLinear coefficient", "`-2 rho B_s`, `2 rho A_s`",
     "centered `D_rho`", "`sign*(D_rho V/rho-V/rho^2)`"),
    ("vector `d_z d_y V^rho`, `d_z d_y V^y`",
     "rotated OddLinear coefficient", "`-B_z`, `A_z`", "centered `d_z`",
     "`-(d_z V^y)/rho`, `(d_z V^rho)/rho`"),
    ("tensor `d_y T_rhorho`, `d_y T_yy`", "TensorSwirl `T_rhoy=s R`",
     "`-2 rho R`, `2 rho R`", "coefficient value",
     "`-2 T_rhoy/rho`, `2 T_rhoy/rho`"),
    ("tensor `d_y T_rhoy`", "TensorPlanarPair `T_rhorho-T_yy=s Q`",
     "`rho Q`", "paired coefficient value", "`(T_rhorho-T_yy)/rho`"),
    ("tensor `d_y T_rhoz`, `d_y T_yz`", "OddLinear `rho U`, `rho V`",
     "`-V`, `U`", "coefficient value", "`-T_yz/rho`, `T_rhoz/rho`"),
    ("tensor `d_y^2 T_rhorho`", "TensorPlanarPair `P+s Q`, `P`",
     "`2(P_s+s Q_s)`", "centered `D_rho` and paired values",
     "`D_rho T_rhorho/rho-2(T_rhorho-T_yy)/rho^2`"),
    ("tensor `d_y^2 T_yy`", "TensorPlanarPair `P+s Q`, `P`",
     "`2(P_s+Q)`", "centered `D_rho` and paired values",
     "`D_rho T_yy/rho+2(T_rhorho-T_yy)/rho^2`"),
    ("tensor `d_y^2 T_rhoy`", "TensorSwirl `s R`", "`-2 R+2 s R_s`",
     "centered `D_rho` and value", "`D_rho T_rhoy/rho-4T_rhoy/rho^2`"),
    ("tensor `d_y^2 T_rhoz`, `d_y^2 T_yz`", "OddLinear `rho U`, `rho V`",
     "`2 rho U_s`, `2 rho V_s`", "centered `D_rho`",
     "`D_rho T/rho-T/rho^2`"),
    ("tensor `d_y^2 T_zz`", "EvenScalar `W(s)`", "`2 W_s`", "centered `D_rho`",
     "`D_rho T_zz/rho`"),
    ("tensor `d_rho d_y T_rhorho`, `d_rho d_y T_yy`", "TensorSwirl `s R`",
     "`-2 R-4 s R_s`, `2 R+4 s R_s`", "centered `D_rho` and value",
     "bulk quotient identities"),
    ("tensor `d_rho d_y T_rhoy`", "TensorPlanarPair `s Q`",
     "`Q+2 s Q_s`", "centered `D_rho` and paired values",
     "bulk quotient identity"),
    ("tensor `d_rho d_y T_rhoz`, `d_rho d_y T_yz`",
     "OddLinear `rho U`, `rho V`", "`-2 rho V_s`, `2 rho U_s`",
     "centered `D_rho`", "bulk quotient identities"),
    ("tensor `d_z d_y` nonzero branches", "regular `R,Q,U,V` coefficients",
     "`-2 rho R_z`, `2 rho R_z`, `rho Q_z`, `-V_z`, `U_z`",
     "centered `d_z`", "analytic quotient of centered `d_z`"),
    ("vector divergence", "OddLinear radial component plus even axial component",
     "`2 A + d_z V^z` on axis", "coefficient value / centered derivatives",
     "`d_rho V^rho+d_z V^z+V^rho/rho`"),
    ("active rho/z first, second, mixed, advection, dissipation",
     "parity-extended scalar/vector/tensor", "ordinary Cartesian action",
     "none", "unchanged centered `Dx/Dxx/Dxy/Lx/Diss`"),
)


SOURCE_MARKERS = (
    "VectorSecondSuppressed",
    "VectorMixedSuppressed", "TensorSecondSuppressed", "TensorMixedSuppressed",
    "return ActiveFirst(RhoDirection(), field) / rho_;",
    "const Real radial_derivative = ActiveFirst(RhoDirection(), component, field);",
    "const Real radial_derivative = ActiveFirst(RhoDirection(), a, b, field);",
)

FORBIDDEN_SOURCE_MARKERS = (
    "NearAxisCell", "TargetLayer", "RegularCoefficientDerivative",
    "EvenCoefficientDerivative", "OddCoefficientDerivative",
    "QuadraticCoefficientDerivative", "QuadraticDifferenceCoefficientDerivative",
)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def render() -> str:
    lines = [
        "# Generated half-plane SO(2) operator inventory", "",
        "This file is generated by `tst/unit/z4c/generate_z4c_cartoon_operator_table.py`.",
        "Do not edit it by hand. Here `s=rho^2`. Every active half-cell uses",
        "the same bulk SO(2) quotient identity with the centered radial derivative",
        "through parity-filled ghost cells. No active point lies at `rho=0`, and no",
        "layer-dependent regular-coefficient reconstruction is present.", "",
    ]
    lines += ["", "## Provider branch inventory", "",
              "The tensor representation is `T_rhorho=P+sQ`, `T_yy=P`,",
              "`T_rhoy=sR`, `T_rhoz=rho U`, `T_yz=rho V`, and `T_zz=W`.", "",
              "| provider branch | regularity class | regular continuum form | discrete primitive | implemented bulk form |",
              "| --- | --- | --- | --- | --- |"]
    lines.extend(f"| {branch} | {regularity} | {continuum} | {primitive} | {direct} |"
                 for branch, regularity, continuum, primitive, direct in OPERATORS)
    lines += ["", "All active rows use the centered O2/O4/O6 radial stencil for",
              "`NGHOST=2/3/4`, including the parity-extended half-cell layers.",
              "`Q=(T_rhorho-T_yy)/rho^2` and",
              "`R=T_rhoy/rho^2` are paired regularity coefficients, not independent fields.",
              "The diagnostic-axis branches use analytic limits and are not active evolution",
              "cell closures because no active cell lies at `rho=0`.", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    root = args.source_dir.resolve()
    source = (root / "src/z4c/cartoon_derivatives.hpp").read_text(encoding="utf-8")
    for marker in SOURCE_MARKERS:
        require(marker in source, f"production provider lacks inventory marker {marker!r}")
    for marker in FORBIDDEN_SOURCE_MARKERS:
        require(marker not in source,
                f"production provider retains layer-dependent marker {marker!r}")
    destination = root / "docs/z4c_cartoon_half_plane_operator_table.md"
    expected = render()
    if args.write:
        destination.write_text(expected, encoding="utf-8")
    else:
        require(destination.is_file(), "generated operator table is missing")
        require(destination.read_text(encoding="utf-8") == expected,
                "generated operator table is stale")
    print("half-plane SO(2) direct-operator inventory verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
