#!/usr/bin/env python3
"""Enforced numeric goldens for the lightweight Cartesian Z4c production run."""

from __future__ import annotations

import argparse
import hashlib
import math
import pathlib
import struct
import subprocess
import sys


# These are metadata-independent hashes over the decoded Real payload.  State,
# history, and Weyl values were generated by exact base 1cabc27b using the same
# deck.  The sixth-order diagnostic is also exact-base data.  The second- and
# fourth-order diagnostics are reviewed tip goldens because the exact-base
# hard-coded fourth-order diagnostic reads out of bounds at those ghost widths.
STATE_FINAL = {
    2: "8861ca727b8fd993f52789af1274c79a63e3ba30c26a15ec24777d8056404908",
    4: "589d3cac15b1aa597aeb553b5816f4deb5c7472a8b7913543393d4bc4169192a",
    6: "ea18920759312a154b076577635d2b6985456b6332d4d768a89801c2d2c3e9eb",
}
DIAGNOSTIC_FINAL = {
    2: "407fdef04d7374eb15f28fe4d36a8fb7a1845935da3fb7888673e01698822d9b",
    4: "8d8d3541c0ee2e126e980bca42d83a0bfe0e956843758d63957d92024365dc06",
    6: "6a98a1d3ffa28d1f12f1ef0929fbcc06424a4f6590cb6073ba9cbbb4fc4bb911",
}
HISTORY_NUMERIC = {
    2: "03ac77b2a435047ea4601793e4992e03c54a7344fd73651a358d19e0fe9db6ab",
    4: "d25617fbdfc521297483351659a0c7f13cfacc598d0b8f09e26a7c3e832c5e00",
    6: "1abb880df6a73aad6a95edfb2ea1c215c3573466a7d7cd5ab627b7611f18bcdb",
}
WEYL_REAL_NUMERIC = {
    2: "7dc20cf6e4e19378d424e28766d79062d50d7c175f20f7c9dc942741ce00b0c5",
    4: "bc373e40f12afa9d650846048fa5c28bd0273a1e087092862bb3bce61f84a5bc",
    6: "64ab42aaab43e23d845291f4e57b193519e97394679f1776352d15af6573c6a4",
}
WEYL_IMAG_NUMERIC = {
    2: "ae0a9821bee135df1eaa41bcf14945f74473bb5b9342ea016d25897adfdbca3d",
    4: "1d80e74b7a0ec4853626513bc68e28ec8d463aae9823f831df9af4e46836c382",
    6: "5b8d9cf22d06518a62c4af45e7aa3382a0509eccada4702eee29dcc695ec4774",
}

# Full-file hashes from the independent base-vs-tip review.  The comparison
# decks use the stable ``cmp_oN`` basename and omit the invalid low-order derived
# output, so these values enforce actual byte identity, including output layout
# and serialization metadata.  History is exact on Serial and compared
# numerically on reduction backends below.
STATE_FILE = {
    2: "9427e92e1413455efe4e523fc9e29a23149e4fc22c257f362b0ede9ec6c82902",
    4: "7ad2a97f748b60bebce1d51915246e84725d431e624cd4676efc9b82545017c3",
    6: "2407544f6c52a4b56d1bdbdaab507a82a1ae706fcef619849488508f0540ad99",
}
HISTORY_FILE = {
    2: "4d2e5a4ea57dab29ee9641fa6b14da56225c2d19eb9776a1e5a8ea1a2676a2a9",
    4: "3e6a9739821cfc4cc5ca1cd329b4fac8774cbcf48cd1e4e9d3b7d24789c8e9d4",
    6: "453d0a6dcddee35236aa598135a19f6f1cd4e5da411f932a0407ced5c43577d2",
}
WEYL_REAL_FILE = {
    2: "39755048f35c0b4a2bf389d63437f8d504fd481b801c838e7a0e13d189cc8084",
    4: "f2cba2b662996531ae7a9516020e21bd1fa6a15b0af2888b2372c3b7be7841ca",
    6: "fb242beb892e054bb13dee45ee99fb5aa6d9097f03efa654dc4c4dfb3774a1cf",
}
WEYL_IMAG_FILE = {
    2: "566dc92dc02f984d606d9e02af12c745790ebbc266be2266f8f5618ccf6fa585",
    4: "c24ce6e7b9d63b2a00b8f62e7f92aa906daa8c9a5d38da9ac4cca2b3bc678a88",
    6: "de37acc70782180605575ca121bf831c3f879d34af153ea7c0b287a423b2d21f",
}
DIAGNOSTIC_ORDER6_FILE = (
    "bbabda2890ff2365bf36d8c43b16a272f517c27241d15062156c80a24a2ed035"
)

HISTORY_GOLDEN = {
    2: [
        [0.0, 0.0125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
         1.0, 0.0, 1.0, 0.0, -1.0, 0.0],
        [0.0125, 0.0125, 9.580565338905522e-17, 1.3321153930629885e-19,
         9.565667808090507e-17, 3.9409422110042874e-21,
         3.833190677210397e-30, 4.7828339097727516e-17,
         4.7828338983173604e-17, 1.5140903364324895e-33, 8.0,
         5.0314534525319154e-17, 1.0, 0.0, 1.0, 0.0, -1.0, 1.0],
    ],
    4: [
        [0.0, 0.0125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
         1.0, 0.0, 1.0, 0.0, -1.0, 0.0],
        [0.0125, 0.0125, 1.5182146176123152e-16, 2.7206838412338443e-19,
         1.5152448150741895e-16, 6.2279674223375566e-21,
         6.2915107651853536e-30, 7.576224055844329e-17,
         7.576224094896906e-17, 1.3194636858954544e-32, 8.0,
         1.8283830367280975e-16, 1.0, 0.0, 1.0, 0.0, -1.0, 1.0],
    ],
    6: [
        [0.0, 0.0125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
         1.0, math.inf, 0.0, 1.0, 0.0, -1.0, 0.0],
        [0.0125, 0.0125, 1.776317462038733e-16, 3.486917197119349e-19,
         1.7725393348355195e-16, 7.280250152363491e-21,
         7.46989195398472e-30, 8.862696819735574e-17,
         8.86269652861887e-17, 6.599968947852674e-33, 8.0,
         1.6686655989656213e-16, 1.0, 6.221256648071102e-13,
         0.0, 1.0, 0.0, -1.0, 1.0],
    ],
}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def numeric_rows(path: pathlib.Path) -> list[list[float]]:
    return [
        [float(value) for value in line.split()]
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def numeric_hash(rows: list[list[float]]) -> str:
    digest = hashlib.sha256()
    for row in rows:
        for value in row:
            digest.update(struct.pack("<d", value))
    return digest.hexdigest()


def file_hash(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def binary_payload_hash(data: dict) -> str:
    digest = hashlib.sha256()
    for name in data["var_names"]:
        digest.update(name.encode("utf-8") + b"\0")
        for block in data["mb_data"][name]:
            digest.update(block.tobytes(order="C"))
    return digest.hexdigest()


def flattened_binary(data: dict):
    for name in data["var_names"]:
        for block in data["mb_data"][name]:
            yield from block.flat


def check_history(order: int, rows: list[list[float]], backend: str,
                  with_kretschmann: bool = True) -> None:
    require(len(rows) == 3, f"order {order}: expected three history rows")
    require(rows[1] == rows[2], f"order {order}: repeated final history row changed")
    if backend == "Serial":
        require(numeric_hash(rows) == HISTORY_NUMERIC[order],
                f"order {order}: exact-base Serial history hash changed")
        return

    # Parallel reductions may change the final few ulps. Compare against the reviewed
    # Serial base with a scale-aware tolerance while keeping state/diagnostic/Weyl exact.
    expected_rows = [HISTORY_GOLDEN[order][0], HISTORY_GOLDEN[order][1],
                     HISTORY_GOLDEN[order][1]]
    if order == 6 and not with_kretschmann:
        expected_rows = [row[:13] + row[14:] for row in expected_rows]
    require([len(row) for row in rows] == [len(row) for row in expected_rows],
            f"order {order}: history shape changed")
    for row_index, (observed, expected) in enumerate(zip(rows, expected_rows)):
        for column, (value, golden) in enumerate(zip(observed, expected)):
            if math.isinf(golden):
                require(value == golden,
                        f"order {order}: history[{row_index},{column}] inf changed")
            else:
                tolerance = (512.0 * sys.float_info.epsilon *
                             max(abs(golden), 1.0e-18) + 1.0e-31)
                require(math.isfinite(value) and abs(value - golden) <= tolerance,
                        f"order {order}: history[{row_index},{column}]={value} "
                        f"differs from {golden} by more than {tolerance}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--athena", type=pathlib.Path, required=True)
    parser.add_argument("--source-dir", type=pathlib.Path, required=True)
    parser.add_argument("--test-dir", type=pathlib.Path, required=True)
    arguments = parser.parse_args()
    sys.path.insert(0, str(arguments.source_dir / "vis/python"))
    import bin_convert  # pylint: disable=import-error,import-outside-toplevel
    import numpy as np  # pylint: disable=import-error,import-outside-toplevel

    config = subprocess.run(
        [str(arguments.athena), "-c"], check=True, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT).stdout
    backend_lines = [line for line in config.splitlines()
                     if "Kokkos default execution space:" in line]
    require(len(backend_lines) == 1, "could not identify Kokkos execution space")
    backend = backend_lines[0].rsplit(":", 1)[1].strip()

    for order in (2, 4, 6):
        case = arguments.test_dir / f"order{order}"
        basename = f"z4c_rhs_policy_o{order}"
        state = bin_convert.read_binary(
            str(case / "bin" / f"{basename}.state.00002.bin"))
        require(binary_payload_hash(state) == STATE_FINAL[order],
                f"order {order}: exact-base final state payload changed")

        diagnostics = []
        for output in range(3):
            diagnostics.append(bin_convert.read_binary(
                str(case / "bin" /
                    f"{basename}.diagnostics.{output:05d}.bin")))
        initial = np.fromiter(flattened_binary(diagnostics[0]), dtype=float)
        require(initial.size == 8192 and np.isnan(initial).all(),
                f"order {order}: t=0 diagnostics must be exactly 8192 unavailable NaNs")
        for output in (1, 2):
            values = np.fromiter(flattened_binary(diagnostics[output]), dtype=float)
            require(values.size == 8192 and np.isfinite(values).all(),
                    f"order {order}: diagnostic output {output} is not wholly finite")
        require(binary_payload_hash(diagnostics[2]) == DIAGNOSTIC_FINAL[order],
                f"order {order}: reviewed final diagnostic payload changed")

        history = numeric_rows(case / f"{basename}.z4c.user.hst")
        check_history(order, history, backend)
        real_weyl = numeric_rows(case / "waveforms/rpsi4_real_0.25.txt")
        imaginary_weyl = numeric_rows(case / "waveforms/rpsi4_imag_0.25.txt")
        require(numeric_hash(real_weyl) == WEYL_REAL_NUMERIC[order],
                f"order {order}: exact-base real Weyl values changed")
        require(numeric_hash(imaginary_weyl) == WEYL_IMAG_NUMERIC[order],
                f"order {order}: exact-base imaginary Weyl values changed")

        exact_case = arguments.test_dir / f"exact_base_order{order}"
        exact_basename = f"cmp_o{order}"
        exact_state = exact_case / "bin" / f"{exact_basename}.state.00002.bin"
        exact_history = exact_case / f"{exact_basename}.z4c.user.hst"
        exact_real = exact_case / "waveforms/rpsi4_real_0.25.txt"
        exact_imaginary = exact_case / "waveforms/rpsi4_imag_0.25.txt"
        require(file_hash(exact_state) == STATE_FILE[order],
                f"order {order}: exact-base state file bytes changed")
        require(file_hash(exact_real) == WEYL_REAL_FILE[order],
                f"order {order}: exact-base real Weyl file bytes changed")
        require(file_hash(exact_imaginary) == WEYL_IMAG_FILE[order],
                f"order {order}: exact-base imaginary Weyl file bytes changed")
        if backend == "Serial":
            require(file_hash(exact_history) == HISTORY_FILE[order],
                    f"order {order}: exact-base Serial history file bytes changed")
        else:
            check_history(order, numeric_rows(exact_history), backend,
                          with_kretschmann=False)

    exact_diagnostic = (arguments.test_dir / "exact_base_diagnostic_order6" /
                        "bin/cmp_diag_o6.diagnostics.00002.bin")
    require(file_hash(exact_diagnostic) == DIAGNOSTIC_ORDER6_FILE,
            "order 6 exact-base diagnostic file bytes changed")

    print(f"Enforced Cartesian Z4c base/golden regression passed on {backend}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (RuntimeError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
