#!/usr/bin/env python3
"""Locate KO-scan curvature and constraint extrema in existing outputs.

This is an offline reader.  It never advances AthenaK or modifies a run.  The
curvature census reads every existing ``*.curvature.*.bin`` snapshot supplied
for a dissipation case, deduplicates segment-boundary snapshots by physical
time, and records both the campaign-wide and terminal max-|Kretschmann|
locations.  Constraint extrema are summarized from the production-matched
``ko_radial_constraints.csv`` generated by ``analyze_ko_scan.py``.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import math
from pathlib import Path
from typing import Any

import numpy as np


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def load_reader(source: Path):
    path = source / "vis/python/bin_convert.py"
    spec = importlib.util.spec_from_file_location("ko_extrema_bin_convert", path)
    require(spec is not None and spec.loader is not None, f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.read_binary


def parse_case(value: str) -> tuple[str, list[Path]]:
    try:
        diss, roots = value.split("=", 1)
    except ValueError as error:
        raise argparse.ArgumentTypeError("case must be DISS=ROOT[,ROOT,...]") from error
    paths = [Path(item) for item in roots.split(",") if item]
    if not diss or not paths:
        raise argparse.ArgumentTypeError("case must be DISS=ROOT[,ROOT,...]")
    return diss, paths


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    require(bool(rows), f"no rows for {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def curvature_snapshot(path: Path, reader) -> dict[str, Any]:
    data = reader(str(path))
    name = "z4c_Kretschmann"
    require(name in data["var_names"], f"{path}: missing {name}")
    best: dict[str, Any] | None = None
    for block, bounds in enumerate(np.asarray(data["mb_geometry"], dtype=float)):
        raw = np.asarray(data["mb_data"][name][block], dtype=float)
        require(raw.ndim == 3 and raw.shape[0] == 1, f"{path}: unexpected shape {raw.shape}")
        values = raw[0]
        require(np.isfinite(values).all(), f"{path}: nonfinite Kretschmann data")
        nj, ni = values.shape
        rho = np.linspace(bounds[0], bounds[1], ni)
        zed = np.linspace(bounds[2], bounds[3], nj)
        flat = int(np.argmax(np.abs(values)))
        j, i = np.unravel_index(flat, values.shape)
        candidate = {
            "time": float(data["time"]),
            "cycle": int(data["cycle"]),
            "leaf_count": int(data["n_mbs"]),
            "max_abs_kretschmann": float(abs(values[j, i])),
            "signed_kretschmann": float(values[j, i]),
            "rho": float(rho[i]),
            "z": float(zed[j]),
            "logical_level": int(np.asarray(data["mb_logical"])[block, 3]),
            "logical_lx1": int(np.asarray(data["mb_logical"])[block, 0]),
            "logical_lx2": int(np.asarray(data["mb_logical"])[block, 1]),
            "logical_lx3": int(np.asarray(data["mb_logical"])[block, 2]),
            "source_file": str(path),
        }
        if best is None or candidate["max_abs_kretschmann"] > best["max_abs_kretschmann"]:
            best = candidate
    require(best is not None, f"{path}: no MeshBlocks")
    return best


def read_constraint_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream))
    require(bool(rows), f"{path}: no constraint rows")
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--case", action="append", type=parse_case, required=True,
                        help="DISS=ROOT[,ROOT,...]; repeat once per dissipation")
    parser.add_argument("--constraint-csv", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    reader = load_reader(args.source)

    snapshot_rows: list[dict[str, Any]] = []
    summary_rows: list[dict[str, Any]] = []
    for diss, roots in args.case:
        by_time: dict[float, dict[str, Any]] = {}
        for root in roots:
            paths = sorted((root / "bin/rank_00000000").glob("*.curvature.*.bin"))
            require(bool(paths), f"{root}: no curvature binaries")
            for path in paths:
                row = curvature_snapshot(path, reader)
                by_time[round(float(row["time"]), 13)] = row
        rows = [by_time[key] for key in sorted(by_time)]
        for row in rows:
            snapshot_rows.append({"diss": diss, **row})
        peak = max(rows, key=lambda row: row["max_abs_kretschmann"])
        terminal = rows[-1]
        for disposition, row in (("campaign_peak", peak), ("terminal_snapshot", terminal)):
            summary_rows.append({"diss": diss, "quantity": "maxAbsKret",
                                 "disposition": disposition, **row})

    write_csv(args.output / "ko_curvature_extrema_by_snapshot.csv", snapshot_rows)
    write_csv(args.output / "ko_extrema_summary.csv", summary_rows)

    if args.constraint_csv is not None:
        rows = [row for row in read_constraint_rows(args.constraint_csv)
                if row["region"] == "full"]
        require(bool(rows), "constraint CSV has no full-domain rows")
        constraint_summary: list[dict[str, Any]] = []
        for diss in sorted({row["diss"] for row in rows}, key=float):
            selected_diss = [row for row in rows if row["diss"] == diss]
            for field in ("C", "H", "M", "Z"):
                selected = [row for row in selected_diss if row["field"] == field]
                require(bool(selected), f"missing {diss} {field}")
                peak = max(selected, key=lambda row: float(row["magnitude"]))
                terminal_time = max(float(row["time"]) for row in selected)
                terminal = min((row for row in selected
                                if math.isclose(float(row["time"]), terminal_time,
                                                rel_tol=0.0, abs_tol=1.0e-12)),
                               key=lambda row: abs(float(row["time"]) - terminal_time))
                for disposition, row in (("sampled_campaign_peak", peak),
                                         ("terminal_snapshot", terminal)):
                    constraint_summary.append({
                        "diss": diss,
                        "quantity": field,
                        "disposition": disposition,
                        "time": row["time"],
                        "axisTau": row["axisTau"],
                        "magnitude": row["magnitude"],
                        "rho": row["magnitude_rho"],
                        "z": row["magnitude_z"],
                    })
        write_csv(args.output / "ko_constraint_extrema_summary.csv", constraint_summary)


if __name__ == "__main__":
    main()
