#!/usr/bin/env python3
"""Generate exact polynomial FD weights for available-halo shifted stencils."""
import argparse
from pathlib import Path
import sympy as s

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('output', type=Path)
args = parser.parse_args()
lines = ['// Generated by analysis/pc_gh_clean_reduction/generate_halo_weights.py.',
         '#ifndef PC_GH_HALO_WEIGHTS_HPP_', '#define PC_GH_HALO_WEIGHTS_HPP_',
         '#include "athena.hpp"', 'namespace pc_gh {',
         'template <int ORDER>', 'KOKKOS_INLINE_FUNCTION',
         'Real HaloDerivativeWeight(int point, int node) {']
for order in [2, 4, 6]:
    lines += [f'  if constexpr (ORDER == {order}) {{',
              f'    const Real weights[{order+1}][{order+1}] = {{']
    for point in range(order+1):
        weights = s.finite_diff_weights(1, list(range(order+1)), point)[1][-1]
        lines += ['      {'+', '.join(f'{v.p}.0/{v.q}.0' for v in weights)+'},']
    lines += ['    };', '    return weights[point][node];', '  }']
lines += ['  return 0.0;', '}', '}  // namespace pc_gh', '#endif', '']
args.output.write_text('\n'.join(lines))
